# Matching investigation

Runs the **real, current matching pipeline** (`backend/app/services/nutrition_mapping.map_item`, `matcher.py`, `base_terms.py`, `fallback_categories.py`, `off_api.py` — nothing reimplemented) against every `receipt_items` row currently in the database.

For each item this shows:
- the **raw text extracted** from the receipt (`raw_name`) and the cleaned `normalized_name`
- the exact **text passed to the OpenFoodFacts search** (`off_query`) — this can differ from `normalized_name` when the matcher falls back to a generalised term (e.g. "Rispentomaten" -> "Tomate")
- the **match currently used** (name, OFF id, confidence, match type, nutrition)
- **how many alternatives** in that same OFF search response also carry usable nutrition data, and their **names** — i.e. candidates that existed but weren't chosen (or weren't even considered, in the fallback case)

Run cells top to bottom. Repeat runs are fast/cheap — `off_api.py` caches every OpenFoodFacts response on disk (`backend/app/services/_off_cache.json`), so only genuinely new queries hit the network.

In [1]:
import sys
from pathlib import Path

# Make sure `backend` is importable regardless of where Jupyter's cwd ends up.
_here = Path.cwd()
for _candidate in [_here, *_here.parents]:
    if (_candidate / "backend").is_dir():
        if str(_candidate) not in sys.path:
            sys.path.insert(0, str(_candidate))
        break
else:
    raise RuntimeError("Could not find the repo root (a parent containing 'backend/') from cwd=" + str(_here))

import pandas as pd

from backend.app.db.supabase import get_all_receipt_items
from backend.app.services import off_api, matcher, base_terms, fallback_categories, nutrition_mapping
from backend.app.models.nutrition import MatchType

pd.set_option("display.max_colwidth", 80)
pd.set_option("display.max_rows", 200)

## Load all receipt items

`get_all_receipt_items()` is the same dev/debug helper the backend itself uses for full-DB sanity checks (see `nutrition_snapshot.build_snapshot_from_all_receipts`) — every row in `receipt_items`, across every receipt and every session.

In [2]:
items = get_all_receipt_items()
print(f"{len(items)} receipt_items rows loaded")
items[0] if items else None

166 receipt_items rows loaded

{'id': '1c75ce3d-07cc-481d-a280-74a6da9e2e75',
 'receipt_id': '96d33a71-ea37-4d0a-a185-54cd2d1734a0',
 'raw_name': 'RUCOLA',
 'normalized_name': 'Rucola',
 'quantity': '1',
 'price': None,
 'confidence': 0.9,
 'unit': '',
 'category': 'Gemüse',
 'matched_product_id': None}

## The investigation function

This mirrors `nutrition_mapping.map_item()` tier-for-tier, calling the exact same production functions (`matcher.match_product`, `base_terms.generic_term`, `fallback_categories.fallback_nutrition`) so the "current match" reported here is identical to what the running app would produce. The only addition is capturing the **full OFF candidate pool** for whichever query tier actually decided the outcome, so we can report how many of those candidates carry real nutrition data and what they're called.

- **Tier 1** — search OFF with the item's own (normalized) name.
- **Tier 2** — if tier 1 found nothing usable, reduce to a generic produce term (e.g. "Rispentomaten" -> "Tomate") and retry.
- **Tier 3** — if neither worked, fall back to a category-based nutrition estimate (no OFF match at all).

In [3]:
def investigate_item(item: dict) -> dict:
    """Run the real matching pipeline for one receipt_items row and report
    the chosen match plus the alternatives it was chosen over."""

    raw_name = item.get("raw_name")
    normalized_name = item.get("normalized_name")
    category = item.get("category")
    # Same name-resolution the production pipeline uses (prefers normalized_name).
    query_name = nutrition_mapping._item_name(item)

    result = {
        "receipt_item_id": item.get("id"),
        "receipt_id": item.get("receipt_id"),
        "raw_name": raw_name,
        "normalized_name": normalized_name,
        "off_query": None,
        "match_tier": None,
        "error": None,
    }

    if not query_name:
        result.update({
            "match_type": "none", "matched_name": None, "off_id": None,
            "confidence": 0.0, "data_source": "none",
            "match_calories": None, "match_protein": None, "match_fiber": None,
            "match_sugar": None, "match_nova": None,
            "n_candidates_returned": 0, "n_candidates_with_nutrition": 0,
            "n_alternatives_with_nutrition": 0, "alternative_names_with_nutrition": [],
        })
        return result

    try:
        # Tier 1: direct query -- identical call to nutrition_mapping.map_item.
        tier1_candidates = off_api.search_products(query_name)
        tier1_match = matcher.match_product(query_name)

        chosen = None
        tier = None
        pool = tier1_candidates
        query_used = query_name

        if tier1_match is not None:
            chosen = tier1_match
            tier = 1
        else:
            generic = base_terms.generic_term(query_name)
            if generic:
                tier2_candidates = off_api.search_products(generic)
                tier2_match = matcher.match_product(generic, prefer_low_processed=True)
                if tier2_match is not None:
                    # Mirror map_item's relabeling of a generic-term hit.
                    tier2_match.parsed_item_name = query_name
                    tier2_match.match_type = MatchType.FUZZY
                    tier2_match.confidence = round(min(tier2_match.confidence, 0.7), 3)
                    tier2_match.data_source = f"OpenFoodFacts (generic: {generic})"
                    chosen = tier2_match
                    tier = 2
                    pool = tier2_candidates
                    query_used = generic

        if chosen is None:
            chosen = fallback_categories.fallback_nutrition(query_name, category)
            tier = 3

        # Nutrition availability across the candidate pool that decided this outcome.
        pool_with_nutrition = []
        for c in pool:
            nutri = off_api.extract_nutrition(c)
            if matcher._has_usable_nutrition(nutri):
                pool_with_nutrition.append(off_api.product_display_name(c) or "(no name)")

        # "Alternatives" = candidates with nutrition data that were NOT the chosen match.
        alt_names = list(pool_with_nutrition)
        if chosen.matched_name in alt_names:
            alt_names.remove(chosen.matched_name)

        nut = chosen.nutrition
        result.update({
            "off_query": query_used,
            "match_tier": tier,
            "match_type": chosen.match_type.value,
            "matched_name": chosen.matched_name,
            "off_id": chosen.off_id,
            "confidence": chosen.confidence,
            "data_source": chosen.data_source,
            "match_calories": nut.calories_kcal if nut else None,
            "match_protein": nut.protein_g if nut else None,
            "match_fiber": nut.fiber_g if nut else None,
            "match_sugar": nut.sugar_g if nut else None,
            "match_nova": nut.processed_score if nut else None,
            "n_candidates_returned": len(pool),
            "n_candidates_with_nutrition": len(pool_with_nutrition),
            "n_alternatives_with_nutrition": len(alt_names),
            "alternative_names_with_nutrition": alt_names,
        })
    except Exception as e:
        result["error"] = f"{type(e).__name__}: {e}"

    return result

## Run it over every receipt item

Cached OFF lookups make repeat runs fast; a first run against many never-before-seen items will be slower (one OpenFoodFacts request per new query).

In [4]:
rows = []
for i, item in enumerate(items):
    rows.append(investigate_item(item))
    if (i + 1) % 25 == 0 or (i + 1) == len(items):
        print(f"...{i + 1}/{len(items)}")

df = pd.DataFrame(rows)
print(df.shape)

errors = df[df["error"].notna()]
if len(errors):
    print(f"\n{len(errors)} item(s) errored:")
    display(errors[["raw_name", "error"]])

...25/166
...50/166
...75/166
...100/166
...125/166
...150/166
...166/166
(166, 21)

## Full results table

One row per receipt item: raw text -> OFF query -> current match -> alternatives that were passed over.

In [5]:
display_cols = [
    "raw_name", "normalized_name", "off_query", "match_tier", "match_type",
    "matched_name", "off_id", "confidence", "data_source",
    "match_calories", "match_protein", "match_fiber", "match_sugar", "match_nova",
    "n_candidates_returned", "n_candidates_with_nutrition",
    "n_alternatives_with_nutrition", "alternative_names_with_nutrition",
]
df[display_cols]

,raw_name,normalized_name,off_query,match_tier,match_type,matched_name,off_id,confidence,data_source,match_calories,match_protein,match_fiber,match_sugar,match_nova,n_candidates_returned,n_candidates_with_nutrition,n_alternatives_with_nutrition,alternative_names_with_nutrition
0,RUCOLA,Rucola,Rucola,1,fuzzy,Pesto basilic roquette basilicum en rucola,3560071462475,0.850,OpenFoodFacts,428.000000,4.400000,1.800000,2.300000,4.0,5,5,4,"[Pesto Basilico e Rucula, Pizza Rucola Ristorante, Brotaufstrich pflanzlich ..."
1,RADIESCHEN,Radieschen,Radieschen,3,fallback,NaN,NaN,0.300,fallback_category:vegetable,40.000000,2.000000,3.000000,3.000000,1.0,5,0,0,[]
2,LAUCHZWIEBELN,Lauchzwiebeln,Lauchzwiebeln,1,fuzzy,"Couscoussalat mit Paprika, Salzlakenkäse und Lauchzwiebeln",4337256035347,0.850,OpenFoodFacts,210.000000,4.400000,1.800000,3.900000,3.0,5,4,3,"[Obazda Lauchzwiebeln, Bulgursalat mit Lauchzwiebeln und Gemüse, Bulgursalat..."
3,KOHLRABI,Kohlrabi,Kohlrabi,1,fuzzy,Kohlrabi G-Rahm-Gemüse,4250241201186,0.850,OpenFoodFacts,48.000000,1.200000,1.300000,2.100000,3.0,5,3,2,"[Superfood brussels sprouts, napa cabbage, kohlrabi, broccoli, carrots & kal..."
4,BRÜHEN IM GLAS,Brühe im Glas,Brühe im Glas,3,fallback,NaN,NaN,0.300,fallback_category:other,150.000000,3.000000,1.000000,5.000000,3.0,0,0,0,[]
5,KOKOSNUSSMILCH,Kokosnussmilch,Kokosnussmilch,1,exact,Kokosnussmilch,4335619110823,1.000,OpenFoodFacts,170.000000,2.000000,0.000000,2.000000,4.0,5,5,4,"[Kokosnussmilch Klassik, kokosnuss milch, Kokosnussmilch cremig, Kokosnussmi..."
6,FLAMMKUCHENTEIG,Flammkuchenteig,Flammkuchenteig,1,exact,Flammkuchenteig,9120003416217,1.000,OpenFoodFacts,264.000000,7.800000,1.500000,2.700000,4.0,5,5,4,"[Frischer Flammkuchenteig, Flammkuchenteig Dinkel, Flammkuchenteig auf Backp..."
7,PAPRIKA MIX,Paprika Mix,Paprika Mix,1,exact,Chilli & paprika mix,8711299023107,1.000,OpenFoodFacts,484.000000,8.000000,0.000000,7.200000,4.0,5,5,4,[Crevettes purée de patate douce au paprika fumé légumes verts sauce chimich...
8,REISNUDELN 200G,Reisnudeln,Reisnudeln,1,exact,Reisnudeln,8850521950368,1.000,OpenFoodFacts,340.000000,8.000000,2.000000,2.000000,1.0,5,5,4,"[Nudeln-Reisnudeln Pad Thai, Gua Thai Reisnudeln, Nudeln aus Naturreis, Nudeln]"
9,HIRTENKÄSE,Hirtenkäse,Hirtenkäse,1,fuzzy,High Protein Hirtenkäse Jalapeno,4056489451273,0.850,OpenFoodFacts,144.000000,24.500000,NaN,1.300000,NaN,5,5,4,"[High Protein Hirtenkäse, Hirtenkäse traditionell (Gazi), Hirtenkäse Traditi..."
10,SPAN. GRÜNE/GESCHW.OLI,Spanische Oliven,Spanische Oliven,1,exact,Spanische Oliven,4002239401302,1.000,OpenFoodFacts,145.000000,1.000000,NaN,0.200000,3.0,5,5,4,"[Spanische grüne Oliven mit Stein, Spanische Grüne Manzanilla-Oliven, entste..."
11,G&G Buttercroiss.,G&G Buttercroissant,G&G Buttercroissant,3,fallback,NaN,NaN,0.300,fallback_category:grain,340.000000,9.000000,7.000000,2.000000,2.0,0,0,0,[]
12,G&G Vollk.Sandwich,G&G Vollkorn Sandwich,G&G Vollkorn Sandwich,3,fallback,NaN,NaN,0.300,fallback_category:grain,340.000000,9.000000,7.000000,2.000000,2.0,0,0,0,[]
13,G&G Tomaten g,G&G Tomaten,tomate,2,fuzzy,Tomato-Ketchup,87157215,0.700,OpenFoodFacts (generic: tomate),102.000000,1.200000,NaN,22.800000,3.0,5,5,4,"[sauce tomate cuisinée, Basilico, Chips de lentilles saveur tomate mozza, Le..."
14,Tony's Great Bits,Tony's Great Bits,Tony's Great Bits,3,fallback,NaN,NaN,0.300,fallback_category:snack,470.000000,6.000000,3.000000,25.000000,4.0,0,0,0,[]
15,G&G H-Schmand,G&G H-Schmand,G&G H-Schmand,3,fallback,NaN,NaN,0.300,fallback_category:dairy,90.000000,6.000000,0.000000,5.000000,2.0,0,0,0,[]
16,G&G rei.Butt.,G&G Reibekäse,G&G Reibekäse,3,fallback,NaN,NaN,0.300,fallback_category:dairy,90.000000,6.000000,0.000000,5.000000,2.0,0,0,0,[]
17,"AB Bud 6x0,3l MW",AB Bud Bier,AB Bud Bier,3,fallback,NaN,NaN,0.300,fallback_category:drink,42.000000,0.000000,0.000000,9.000000,4.0,0,0,0,[]
18,"Vollmilch 3,5% 1L","Vollmilch 3,5%","Vollmilch 3,5%",1,fuzzy,"H-Milch 3,5%",4008452027602,0.850,OpenFoodFacts,64.000000,3.500000,0.000000,4.700000,1.0,5,5,4,"[H-Vollmilch 3,5 % Fett, Haltbare Milch 3,8% Fett, Lebkuchen Vollmilch, Voll..."
19,Vollkornbrot 500g,Vollkornbrot,Vollkornbrot,1,exact,Vollkornbrot,3029330004233,1.000,OpenFoodFacts,211.200000,6.800000,10.000000,4.900000,3.0,5,5,4,"[Pain spécial Vollkornbrot au seigle 500g, Pain noir allemand vollkornbrot 5..."
20,"Bananen 1,0 kg",Bananen,Bananen,1,fuzzy,Bananenchips,4008258274019,0.850,OpenFoodFacts,528.000000,1.900000,NaN,14.000000,4.0,5,5,4,"[Bananen Joghurt mit Knuspermüsli Schoko, Schoko Bananen, Protein Knuspermüs..."
21,Bio Eier 10 Stk,Bio Eier,Bio Eier,1,fuzzy,Eier,4061458234696,0.850,OpenFoodFacts,153.000000,13.000000,NaN,0.500000,1.0,5,5,4,"[Vegane Salatmayo, Eier, Vegane Mayo, Eier]"
22,Gouda jung 200g,Gouda jung,Gouda jung,1,exact,Gouda Jung,4335619117907,1.000,OpenFoodFacts,361.000000,25.000000,0.000000,0.100000,3.0,5,5,4,"[Gouda jung in Scheiben, Käse Gouda jung, Gouda Jung, Junger Gouda In Scheib..."
23,Haferflocken 500g,Haferflocken,Haferflocken,1,exact,Haferflocken,20003166,1.000,OpenFoodFacts,372.000000,13.500000,10.000000,0.700000,1.0,5,5,4,"[Hafer Flocken Zart, Blütenzarte Haferflocken, Zarte Haferflocken, Kernige H..."
24,Naturjoghurt 500g,Naturjoghurt,Naturjoghurt,1,fuzzy,"Joghurt mild 3,5 % Fett",4061458028820,0.850,OpenFoodFacts,70.000000,4.300000,NaN,4.800000,1.0,5,5,4,"[Bio Fettarmer Joghurt mild, Cremiger Jogurt - 3,8 % Fett, Joghurt Natur 3,5..."
25,Bulgur Rote Beete,Bulgur Rote Bete,Bulgur Rote Bete,1,fuzzy,Rote Bete Bulgur Salat,02943432,0.850,OpenFoodFacts,100.000000,3.100000,NaN,4.900000,NaN,1,1,0,[]
26,Vollkornbrot 500g,Vollkornbrot,Vollkornbrot,1,exact,Vollkornbrot,3029330004233,1.000,OpenFoodFacts,211.200000,6.800000,10.000000,4.900000,3.0,5,5,4,"[Pain spécial Vollkornbrot au seigle 500g, Pain noir allemand vollkornbrot 5..."
27,"Bananen 1,0 kg",Bananen,Bananen,1,fuzzy,Bananenchips,4008258274019,0.850,OpenFoodFacts,528.000000,1.900000,NaN,14.000000,4.0,5,5,4,"[Bananen Joghurt mit Knuspermüsli Schoko, Schoko Bananen, Protein Knuspermüs..."
28,Bio Eier 10 Stk,Bio Eier,Bio Eier,1,fuzzy,Eier,4061458234696,0.850,OpenFoodFacts,153.000000,13.000000,NaN,0.500000,1.0,5,5,4,"[Vegane Salatmayo, Eier, Vegane Mayo, Eier]"
29,Gouda jung 200g,Gouda jung,Gouda jung,1,exact,Gouda Jung,4335619117907,1.000,OpenFoodFacts,361.000000,25.000000,0.000000,0.100000,3.0,5,5,4,"[Gouda jung in Scheiben, Käse Gouda jung, Gouda Jung, Junger Gouda In Scheib..."
30,Haferflocken 500g,Haferflocken,Haferflocken,1,exact,Haferflocken,20003166,1.000,OpenFoodFacts,372.000000,13.500000,10.000000,0.700000,1.0,5,5,4,"[Hafer Flocken Zart, Blütenzarte Haferflocken, Zarte Haferflocken, Kernige H..."
31,Naturjoghurt 500g,Naturjoghurt,Naturjoghurt,1,fuzzy,"Joghurt mild 3,5 % Fett",4061458028820,0.850,OpenFoodFacts,70.000000,4.300000,NaN,4.800000,1.0,5,5,4,"[Bio Fettarmer Joghurt mild, Cremiger Jogurt - 3,8 % Fett, Joghurt Natur 3,5..."
32,"Vollmilch 3,5% 1L",Bio Vollmilch,Bio Vollmilch,1,exact,Haltbare Bio Vollmilch,4056489379850,1.000,OpenFoodFacts,67.000000,3.200000,0.000000,4.800000,1.0,5,5,4,"[Bio Vollmilch, Vollmilch Schoko Reiswaffeln Bio, ALDI BIO Frische Bio-Vollm..."
33,Lieken Urkorn Fitnessbrot 500g,Lieken Urkorn Fitnessbrot,Lieken Urkorn Fitnessbrot,1,fuzzy,Fitnessbrot mit 5 % Ölsaaten,4009249002277,0.850,OpenFoodFacts,232.727273,9.090909,7.090909,4.363636,3.0,1,1,0,[]
34,Bio Paprika Mix 400g,Bio Paprika Mix,Bio Paprika Mix,1,fuzzy,Chorizo paprika séché 50 jours,4000915108422,0.850,OpenFoodFacts,476.000000,26.000000,NaN,0.000000,3.0,5,1,0,[]
35,"Suesskartoffeln 0,718 kg",Süßkartoffeln,Süßkartoffeln,1,fuzzy,Red lentil & sweet potato noodles | Fusilli aus roten Linsen und Süsskartoffeln,7613413888948,0.889,OpenFoodFacts,354.000000,25.000000,5.900000,4.000000,NaN,5,4,3,"[Nudeln Aus Süßkartoffeln - Hosaku - 500G, Gemüse mit Süßkartoffeln und Huhn..."
36,Avocado vorgereift ST,Vorgereifte Avocado,avocado,2,fuzzy,Avocados,20229030,0.700,OpenFoodFacts (generic: avocado),190.000000,1.900000,3.400000,0.500000,1.0,5,5,4,"[Avocado Oil Spray, All Natural Avocado Oil Mayo, MAYO Real Mayonnaise made ..."
37,"SB JB-Roastbeef ca.280gQS kg 0,294",Roastbeef,Roastbeef,1,exact,Roastbeef,7032069760611,1.000,OpenFoodFacts,110.000000,23.000000,NaN,0.900000,4.0,5,5,4,"[Natural hazelnuts, På lækker Roastbeef, Baguette au roastbeef nature, Roast..."
38,Plattpfirsiche,Plattpfirsiche,Plattpfirsiche,1,exact,Plattpfirsiche,4055379028588,1.000,OpenFoodFacts,39.000000,0.800000,NaN,8.900000,NaN,5,1,0,[]
39,Salatherzen Roma,Salatherzen Roma,Salatherzen Roma,1,fuzzy,Roma Salatherzen,4056489148456,0.850,OpenFoodFacts,14.000000,0.000000,0.900000,0.000000,NaN,1,1,0,[]
40,PORREE,Porree,Porree,1,fuzzy,Porree Rahm-Gemüse,4250241202152,0.850,OpenFoodFacts,66.000000,1.500000,1.300000,2.500000,4.0,5,3,2,"[Wrap - Hähnchen Teriyaki, Porree Paste]"
41,Cocktailrispe,Cocktailrispentomaten,tomate,2,fuzzy,Tomato-Ketchup,87157215,0.700,OpenFoodFacts (generic: tomate),102.000000,1.200000,NaN,22.800000,3.0,5,5,4,"[sauce tomate cuisinée, Basilico, Chips de lentilles saveur tomate mozza, Le..."
42,Gurken Stück x,Gurken,Gurken,1,exact,Gurken,8480000295408,1.000,OpenFoodFacts,19.000000,1.300000,0.600000,0.600000,4.0,5,5,4,"[Cornichons Gurken, Gewürzgurken, KNAX Gewürzgurken, Snack-Gurken]"
43,LINSEN MIT SG,Linsen,Linsen,1,fuzzy,DM Bio Linsenwaffeln 100g 1.35€ 1kg 13.50€,4066447562644,0.850,OpenFoodFacts,367.000000,29.000000,7.200000,1.400000,3.0,5,5,4,"[Linsen Chips Paprika Style, Linsen Waffeln, Linsen Chips Sour Creme Style, ..."
44,apfel x 3,Äpfel,Äpfel,1,fuzzy,c.m. plus Knusper-Müesli Äpfel & Honig,7610023050819,0.850,OpenFoodFacts,428.000000,9.500000,6.700000,19.000000,4.0,5,5,4,"[Vegane Pommersche Apfel und Zwieben, Himbeere Apfel, Apfel naturtrüb Direkt..."
45,hackfleisch 400g,Hackfleisch,Hackfleisch,1,fuzzy,Veganes Mühlen Hack,4000405005217,0.850,OpenFoodFacts,105.000000,18.000000,5.700000,0.500000,4.0,5,4,3,[Puten-Hackfleisch Frisch; gewürzt; zum Braten Aus der Frischetruhe Dauerti...
46,"vollmilch 0,5l",Vollmilch,Vollmilch,1,exact,Vollmilch,4045317058067,1.000,OpenFoodFacts,67.000000,3.300000,NaN,4.800000,1.0,5,5,4,"[H-Milch 3,5%, H-Vollmilch 3,5 % Fett, Haltbare Milch 3,8% Fett, Lebkuchen V..."
47,rote linsen,Rote Linsen,Rote Linsen,1,fuzzy,Rote Linsen Bratlinge,4066447580617,0.850,OpenFoodFacts,334.000000,19.000000,12.000000,5.790000,3.0,5,5,4,"[Fusilli Rote Linsen, Rote Linsen, getrocknet, Rote Linsen Spirelli, Rote Li..."
48,LAUCHZWIEBELN,Lauchzwiebeln,Lauchzwiebeln,1,fuzzy,"Couscoussalat mit Paprika, Salzlakenkäse und Lauchzwiebeln",4337256035347,0.850,OpenFoodFacts,210.000000,4.400000,1.800000,3.900000,3.0,5,4,3,"[Obazda Lauchzwiebeln, Bulgursalat mit Lauchzwiebeln und Gemüse, Bulgursalat..."
49,RADIESCHEN,Radieschen,Radieschen,3,fallback,NaN,NaN,0.300,fallback_category:vegetable,40.000000,2.000000,3.000000,3.000000,1.0,5,0,0,[]
50,FELDSALAT,Feldsalat,Feldsalat,1,exact,Feldsalat,4311527075744,1.000,OpenFoodFacts,16.000000,1.900000,NaN,NaN,1.0,5,2,1,[Bio Feldsalat]
51,CHAMPIGNONS GROSS,Große Champignons,Große Champignons,3,fallback,NaN,NaN,0.300,fallback_category:vegetable,40.000000,2.000000,3.000000,3.000000,1.0,0,0,0,[]
52,GEBÄCKSTANG,Gebäckstange,Gebäckstange,1,fuzzy,Feine Gebäckstange,2007030013527,0.850,OpenFoodFacts,484.000000,9.800000,3.500000,2.600000,NaN,1,1,0,[]
53,OSTFR. TEEMISCHUNG LOS,Lose Osterfrüchtetee Mischung,Lose Osterfrüchtetee Mischung,3,fallback,NaN,NaN,0.300,fallback_category:other,150.000000,3.000000,1.000000,5.000000,3.0,0,0,0,[]
54,"Vollmilch 3,5% 1L",Vollmilch,Vollmilch,1,exact,Vollmilch,4045317058067,1.000,OpenFoodFacts,67.000000,3.300000,NaN,4.800000,1.0,5,5,4,"[H-Milch 3,5%, H-Vollmilch 3,5 % Fett, Haltbare Milch 3,8% Fett, Lebkuchen V..."
55,Vollkornbrot 500g,Vollkornbrot,Vollkornbrot,1,exact,Vollkornbrot,3029330004233,1.000,OpenFoodFacts,211.200000,6.800000,10.000000,4.900000,3.0,5,5,4,"[Pain spécial Vollkornbrot au seigle 500g, Pain noir allemand vollkornbrot 5..."
56,"Bananen 1,0 kg",Bananen,Bananen,1,fuzzy,Bananenchips,4008258274019,0.850,OpenFoodFacts,528.000000,1.900000,NaN,14.000000,4.0,5,5,4,"[Bananen Joghurt mit Knuspermüsli Schoko, Schoko Bananen, Protein Knuspermüs..."
57,Bio Eier 10 Stk,Bio Eier,Bio Eier,1,fuzzy,Eier,4061458234696,0.850,OpenFoodFacts,153.000000,13.000000,NaN,0.500000,1.0,5,5,4,"[Vegane Salatmayo, Eier, Vegane Mayo, Eier]"
58,Gouda jung 200g,Gouda jung,Gouda jung,1,exact,Gouda Jung,4335619117907,1.000,OpenFoodFacts,361.000000,25.000000,0.000000,0.100000,3.0,5,5,4,"[Gouda jung in Scheiben, Käse Gouda jung, Gouda Jung, Junger Gouda In Scheib..."
59,Haferflocken 500g,Haferflocken,Haferflocken,1,exact,Haferflocken,20003166,1.000,OpenFoodFacts,372.000000,13.500000,10.000000,0.700000,1.0,5,5,4,"[Hafer Flocken Zart, Blütenzarte Haferflocken, Zarte Haferflocken, Kernige H..."
60,Naturjoghurt 500g,Naturjoghurt,Naturjoghurt,1,fuzzy,"Joghurt mild 3,5 % Fett",4061458028820,0.850,OpenFoodFacts,70.000000,4.300000,NaN,4.800000,1.0,5,5,4,"[Bio Fettarmer Joghurt mild, Cremiger Jogurt - 3,8 % Fett, Joghurt Natur 3,5..."
61,"Vollmilch 3,5% 1L",Vollmilch,Vollmilch,1,exact,Vollmilch,4045317058067,1.000,OpenFoodFacts,67.000000,3.300000,NaN,4.800000,1.0,5,5,4,"[H-Milch 3,5%, H-Vollmilch 3,5 % Fett, Haltbare Milch 3,8% Fett, Lebkuchen V..."
62,Vollkornbrot 500g,Vollkornbrot,Vollkornbrot,1,exact,Vollkornbrot,3029330004233,1.000,OpenFoodFacts,211.200000,6.800000,10.000000,4.900000,3.0,5,5,4,"[Pain spécial Vollkornbrot au seigle 500g, Pain noir allemand vollkornbrot 5..."
63,"Bananen 1,0 kg",Bananen,Bananen,1,fuzzy,Bananenchips,4008258274019,0.850,OpenFoodFacts,528.000000,1.900000,NaN,14.000000,4.0,5,5,4,"[Bananen Joghurt mit Knuspermüsli Schoko, Schoko Bananen, Protein Knuspermüs..."
64,Bio Eier 10 Stk,Bio Eier,Bio Eier,1,fuzzy,Eier,4061458234696,0.850,OpenFoodFacts,153.000000,13.000000,NaN,0.500000,1.0,5,5,4,"[Vegane Salatmayo, Eier, Vegane Mayo, Eier]"
65,Gouda jung 200g,Gouda jung,Gouda jung,1,exact,Gouda Jung,4335619117907,1.000,OpenFoodFacts,361.000000,25.000000,0.000000,0.100000,3.0,5,5,4,"[Gouda jung in Scheiben, Käse Gouda jung, Gouda Jung, Junger Gouda In Scheib..."
66,Haferflocken 500g,Haferflocken,Haferflocken,1,exact,Haferflocken,20003166,1.000,OpenFoodFacts,372.000000,13.500000,10.000000,0.700000,1.0,5,5,4,"[Hafer Flocken Zart, Blütenzarte Haferflocken, Zarte Haferflocken, Kernige H..."
67,Naturjoghurt 500g,Naturjoghurt,Naturjoghurt,1,fuzzy,"Joghurt mild 3,5 % Fett",4061458028820,0.850,OpenFoodFacts,70.000000,4.300000,NaN,4.800000,1.0,5,5,4,"[Bio Fettarmer Joghurt mild, Cremiger Jogurt - 3,8 % Fett, Joghurt Natur 3,5..."
68,ÖSTERREICHISCHER BERGK,Österreichischer Bergkäse,Österreichischer Bergkäse,1,exact,Österreichischer Bergkäse,2204414004021,1.000,OpenFoodFacts,386.000000,27.000000,NaN,NaN,NaN,5,5,4,"[Original österreichischer Bergkäse, Österreichischer Bergkäse, 45 % Fett i...."
69,TK DR. OETKER OFENFR.,Dr. Oetker Ofenfrische Pizza,Dr. Oetker Ofenfrische Pizza,1,fuzzy,Die Ofenfrische Margherita,4001724015420,0.850,OpenFoodFacts,226.109661,9.800000,1.900000,2.900000,4.0,5,5,4,"[Die Ofenfrische Thunfisch, Die Ofenfrische Speciale, Pizza Salami Die Ofenf..."
70,BIO OLIVENÖL,Bio Olivenöl,Bio Olivenöl,1,exact,Bio Olivenöl Nativ Extra,4045178002322,1.000,OpenFoodFacts,828.000000,0.000000,NaN,0.000000,2.0,5,4,3,"[Olivenöl nativ extra, Italienisches Olivenöl, Bio olivenöl]"
71,RUCOLA,Rucola,Rucola,1,fuzzy,Pesto basilic roquette basilicum en rucola,3560071462475,0.850,OpenFoodFacts,428.000000,4.400000,1.800000,2.300000,4.0,5,5,4,"[Pesto Basilico e Rucula, Pizza Rucola Ristorante, Brotaufstrich pflanzlich ..."
72,RADIESCHEN,Radieschen,Radieschen,3,fallback,NaN,NaN,0.300,fallback_category:vegetable,40.000000,2.000000,3.000000,3.000000,1.0,5,0,0,[]
73,LAUCHZWIEBELN,Lauchzwiebeln,Lauchzwiebeln,1,fuzzy,"Couscoussalat mit Paprika, Salzlakenkäse und Lauchzwiebeln",4337256035347,0.850,OpenFoodFacts,210.000000,4.400000,1.800000,3.900000,3.0,5,4,3,"[Obazda Lauchzwiebeln, Bulgursalat mit Lauchzwiebeln und Gemüse, Bulgursalat..."
74,KOHLRABI,Kohlrabi,Kohlrabi,1,fuzzy,Kohlrabi G-Rahm-Gemüse,4250241201186,0.850,OpenFoodFacts,48.000000,1.200000,1.300000,2.100000,3.0,5,3,2,"[Superfood brussels sprouts, napa cabbage, kohlrabi, broccoli, carrots & kal..."
75,BRÜHEN IM GLAS,Brühe im Glas,Brühe im Glas,3,fallback,NaN,NaN,0.300,fallback_category:other,150.000000,3.000000,1.000000,5.000000,3.0,0,0,0,[]
76,KOKOSNUSSMILCH,Kokosnussmilch,Kokosnussmilch,1,exact,Kokosnussmilch,4335619110823,1.000,OpenFoodFacts,170.000000,2.000000,0.000000,2.000000,4.0,5,5,4,"[Kokosnussmilch Klassik, kokosnuss milch, Kokosnussmilch cremig, Kokosnussmi..."
77,FLAMMKUCHENTEIG,Flammkuchenteig,Flammkuchenteig,1,exact,Flammkuchenteig,9120003416217,1.000,OpenFoodFacts,264.000000,7.800000,1.500000,2.700000,4.0,5,5,4,"[Frischer Flammkuchenteig, Flammkuchenteig Dinkel, Flammkuchenteig auf Backp..."
78,PAPRIKA MIX,Paprika Mix,Paprika Mix,1,exact,Chilli & paprika mix,8711299023107,1.000,OpenFoodFacts,484.000000,8.000000,0.000000,7.200000,4.0,5,5,4,[Crevettes purée de patate douce au paprika fumé légumes verts sauce chimich...
79,REISNUDELN 200G,Reisnudeln,Reisnudeln,1,exact,Reisnudeln,8850521950368,1.000,OpenFoodFacts,340.000000,8.000000,2.000000,2.000000,1.0,5,5,4,"[Nudeln-Reisnudeln Pad Thai, Gua Thai Reisnudeln, Nudeln aus Naturreis, Nudeln]"
80,HIRTENKÄSE,Hirtenkäse,Hirtenkäse,1,fuzzy,High Protein Hirtenkäse Jalapeno,4056489451273,0.850,OpenFoodFacts,144.000000,24.500000,NaN,1.300000,NaN,5,5,4,"[High Protein Hirtenkäse, Hirtenkäse traditionell (Gazi), Hirtenkäse Traditi..."
81,SPAN. GRÜNE/GESCHW.OLI,Spanische Oliven,Spanische Oliven,1,exact,Spanische Oliven,4002239401302,1.000,OpenFoodFacts,145.000000,1.000000,NaN,0.200000,3.0,5,5,4,"[Spanische grüne Oliven mit Stein, Spanische Grüne Manzanilla-Oliven, entste..."
82,Schokolade 3kg,Schokolade,Schokolade,1,fuzzy,Dunkle Schokolade mit ganzen Haselnüssen,20815356,0.850,OpenFoodFacts,587.000000,8.600000,8.000000,30.000000,4.0,5,5,4,"[Toffifee 15er, Sweet & saltynut, Haselnuss Schokolade, Toffifee weiße Schok..."
83,"Vollmilch 3,5% 1L",Vollmilch,Vollmilch,1,exact,Vollmilch,4045317058067,1.000,OpenFoodFacts,67.000000,3.300000,NaN,4.800000,1.0,5,5,4,"[H-Milch 3,5%, H-Vollmilch 3,5 % Fett, Haltbare Milch 3,8% Fett, Lebkuchen V..."
84,Vollkornbrot 500g,Vollkornbrot,Vollkornbrot,1,exact,Vollkornbrot,3029330004233,1.000,OpenFoodFacts,211.200000,6.800000,10.000000,4.900000,3.0,5,5,4,"[Pain spécial Vollkornbrot au seigle 500g, Pain noir allemand vollkornbrot 5..."
85,"Bananen 1,0 kg",Bananen,Bananen,1,fuzzy,Bananenchips,4008258274019,0.850,OpenFoodFacts,528.000000,1.900000,NaN,14.000000,4.0,5,5,4,"[Bananen Joghurt mit Knuspermüsli Schoko, Schoko Bananen, Protein Knuspermüs..."
86,Bio Eier 10 Stk,Bio Eier,Bio Eier,1,fuzzy,Eier,4061458234696,0.850,OpenFoodFacts,153.000000,13.000000,NaN,0.500000,1.0,5,5,4,"[Vegane Salatmayo, Eier, Vegane Mayo, Eier]"
87,Gouda jung 200g,Gouda jung,Gouda jung,1,exact,Gouda Jung,4335619117907,1.000,OpenFoodFacts,361.000000,25.000000,0.000000,0.100000,3.0,5,5,4,"[Gouda jung in Scheiben, Käse Gouda jung, Gouda Jung, Junger Gouda In Scheib..."
88,Haferflocken 500g,Haferflocken,Haferflocken,1,exact,Haferflocken,20003166,1.000,OpenFoodFacts,372.000000,13.500000,10.000000,0.700000,1.0,5,5,4,"[Hafer Flocken Zart, Blütenzarte Haferflocken, Zarte Haferflocken, Kernige H..."
89,Naturjoghurt 500g,Naturjoghurt,Naturjoghurt,1,fuzzy,"Joghurt mild 3,5 % Fett",4061458028820,0.850,OpenFoodFacts,70.000000,4.300000,NaN,4.800000,1.0,5,5,4,"[Bio Fettarmer Joghurt mild, Cremiger Jogurt - 3,8 % Fett, Joghurt Natur 3,5..."
90,"Vollmilch 3,5% 1L","Vollmilch 3,5%","Vollmilch 3,5%",1,fuzzy,"H-Milch 3,5%",4008452027602,0.850,OpenFoodFacts,64.000000,3.500000,0.000000,4.700000,1.0,5,5,4,"[H-Vollmilch 3,5 % Fett, Haltbare Milch 3,8% Fett, Lebkuchen Vollmilch, Voll..."
91,Vollkornbrot 500g,Vollkornbrot,Vollkornbrot,1,exact,Vollkornbrot,3029330004233,1.000,OpenFoodFacts,211.200000,6.800000,10.000000,4.900000,3.0,5,5,4,"[Pain spécial Vollkornbrot au seigle 500g, Pain noir allemand vollkornbrot 5..."

In [9]:
df[df["match_type"]=="fallback"]

,receipt_item_id,receipt_id,raw_name,normalized_name,off_query,match_tier,error,match_type,matched_name,off_id,...,data_source,match_calories,match_protein,match_fiber,match_sugar,match_nova,n_candidates_returned,n_candidates_with_nutrition,n_alternatives_with_nutrition,alternative_names_with_nutrition
1,034facb3-962b-49d2-b812-0e6041bc1f6d,96d33a71-ea37-4d0a-a185-54cd2d1734a0,RADIESCHEN,Radieschen,Radieschen,3,None,fallback,NaN,NaN,...,fallback_category:vegetable,40.0,2.0,3.0,3.0,1.0,5,0,0,[]
4,45925cb6-4357-4dcf-a439-1a522af21a9a,96d33a71-ea37-4d0a-a185-54cd2d1734a0,BRÜHEN IM GLAS,Brühe im Glas,Brühe im Glas,3,None,fallback,NaN,NaN,...,fallback_category:other,150.0,3.0,1.0,5.0,3.0,0,0,0,[]
11,7377b6aa-020a-40e4-9157-73f40e5d236c,2aaff573-a462-4920-8342-8e966f8c2abe,G&G Buttercroiss.,G&G Buttercroissant,G&G Buttercroissant,3,None,fallback,NaN,NaN,...,fallback_category:grain,340.0,9.0,7.0,2.0,2.0,0,0,0,[]
12,7c1ee144-78da-44a7-ad1f-46c50d115665,2aaff573-a462-4920-8342-8e966f8c2abe,G&G Vollk.Sandwich,G&G Vollkorn Sandwich,G&G Vollkorn Sandwich,3,None,fallback,NaN,NaN,...,fallback_category:grain,340.0,9.0,7.0,2.0,2.0,0,0,0,[]
14,d33debe4-5668-4ce8-bb1c-4e233a3a380f,2aaff573-a462-4920-8342-8e966f8c2abe,Tony's Great Bits,Tony's Great Bits,Tony's Great Bits,3,None,fallback,NaN,NaN,...,fallback_category:snack,470.0,6.0,3.0,25.0,4.0,0,0,0,[]
15,c4313223-ca61-4054-bfc4-1fac971e941c,2aaff573-a462-4920-8342-8e966f8c2abe,G&G H-Schmand,G&G H-Schmand,G&G H-Schmand,3,None,fallback,NaN,NaN,...,fallback_category:dairy,90.0,6.0,0.0,5.0,2.0,0,0,0,[]
16,5bfda5b7-bb8b-4a8c-9f5f-e9b245d41c6e,2aaff573-a462-4920-8342-8e966f8c2abe,G&G rei.Butt.,G&G Reibekäse,G&G Reibekäse,3,None,fallback,NaN,NaN,...,fallback_category:dairy,90.0,6.0,0.0,5.0,2.0,0,0,0,[]
17,45998eb7-6031-469f-a5b8-d6c70e484b20,2aaff573-a462-4920-8342-8e966f8c2abe,"AB Bud 6x0,3l MW",AB Bud Bier,AB Bud Bier,3,None,fallback,NaN,NaN,...,fallback_category:drink,42.0,0.0,0.0,9.0,4.0,0,0,0,[]
49,04633f58-e8f9-4c57-9bf0-1afe619bdb65,b7c967e6-6dd5-4963-b767-e4a33d94c897,RADIESCHEN,Radieschen,Radieschen,3,None,fallback,NaN,NaN,...,fallback_category:vegetable,40.0,2.0,3.0,3.0,1.0,5,0,0,[]
51,5abe2ebf-2215-4db0-a32c-c1ef64b65909,b7c967e6-6dd5-4963-b767-e4a33d94c897,CHAMPIGNONS GROSS,Große Champignons,Große Champignons,3,None,fallback,NaN,NaN,...,fallback_category:vegetable,40.0,2.0,3.0,3.0,1.0,0,0,0,[]
53,fcf2743f-f57e-48d8-8cfd-84cc05ec13e0,b7c967e6-6dd5-4963-b767-e4a33d94c897,OSTFR. TEEMISCHUNG LOS,Lose Osterfrüchtetee Mischung,Lose Osterfrüchtetee Mischung,3,None,fallback,NaN,NaN,...,fallback_category:other,150.0,3.0,1.0,5.0,3.0,0,0,0,[]
72,d0d97ae5-3902-42d2-a566-aae4de59a0bc,4d3948ef-06b4-4f1e-9275-2ae871a80b7d,RADIESCHEN,Radieschen,Radieschen,3,None,fallback,NaN,NaN,...,fallback_category:vegetable,40.0,2.0,3.0,3.0,1.0,5,0,0,[]
75,568d1371-25fd-48af-834b-6a9b9f64a5bf,4d3948ef-06b4-4f1e-9275-2ae871a80b7d,BRÜHEN IM GLAS,Brühe im Glas,Brühe im Glas,3,None,fallback,NaN,NaN,...,fallback_category:other,150.0,3.0,1.0,5.0,3.0,0,0,0,[]
117,77e431ec-dcc5-43b7-a743-97cb581290ee,cacd01d0-d604-4596-97a3-aca9fde54151,"Vollmilch 3,5% 1L",Test Milch,Test Milch,3,None,fallback,NaN,NaN,...,fallback_category:dairy,90.0,6.0,0.0,5.0,2.0,1,1,1,[Gouda Jung]
125,8fa52592-3d53-4631-ac4b-4fdf04000c8e,ebbfb862-a9d5-45a4-af99-6ec3066b4932,RADIESCHEN,Radieschen,Radieschen,3,None,fallback,NaN,NaN,...,fallback_category:vegetable,40.0,2.0,3.0,3.0,1.0,5,0,0,[]
129,03966ae1-7910-4c1a-bbc3-771212523fe2,ebbfb862-a9d5-45a4-af99-6ec3066b4932,OSTFR. TEEMISCHUNG LOS,Osterfrüchtetee Mischung lose,Osterfrüchtetee Mischung lose,3,None,fallback,NaN,NaN,...,fallback_category:other,150.0,3.0,1.0,5.0,3.0,0,0,0,[]
137,7e70dd48-0869-442a-8c02-073f1242845f,ad6b0bda-c4c9-4a15-adad-945557edff0d,"Vollmilch 3,5% 1L","Test Milch 3,5%","Test Milch 3,5%",3,None,fallback,NaN,NaN,...,fallback_category:dairy,90.0,6.0,0.0,5.0,2.0,1,1,1,[Gouda Jung]
159,7a3d5d8c-3bb7-4a3c-9119-961d81e52cdf,6f4b5b22-39bc-4c1e-85bb-a24b68ba5162,Xyzzyx Quark Unbekanntes Produkt 12345,Xyzzyx Quark Unbekanntes Produkt 12345,Xyzzyx Quark Unbekanntes Produkt 12345,3,None,fallback,NaN,NaN,...,fallback_category:dairy,90.0,6.0,0.0,5.0,2.0,0,0,0,[]

## Summary stats

In [ ]:
print("match_type counts:")
print(df["match_type"].value_counts())
print("\nmatch_tier counts (1=direct, 2=generic-term retry, 3=category fallback):")
print(df["match_tier"].value_counts(dropna=False))
print("\naverage # alternatives-with-nutrition per row:", round(df["n_alternatives_with_nutrition"].mean(), 2))
print("rows where at least one unused alternative had nutrition data:",
      (df["n_alternatives_with_nutrition"] > 0).sum(), "/", len(df))

## Diagnostics: likely matching problems

Two views worth checking manually (this is what feeds `MATCH-1`/`MATCH-4` in `backlog_structured.md`):

1. **Fallback despite available OFF data** — the item fell back to a coarse category estimate, but the OFF search it ran *did* return candidates with real nutrition data; they just scored below the similarity threshold. Worth checking whether the threshold or the query text is the problem.
2. **Fuzzy matches with unused alternatives** — a match was accepted, but other candidates with nutrition data existed. Not necessarily wrong, but worth a manual eyeball for cases like "Linsen" -> a wafer snack, where a plainer alternative ("Rote Linsen, getrocknet") was sitting right there.

In [6]:
fallback_missed = df[(df["match_type"] == "fallback") & (df["n_candidates_with_nutrition"] > 0)]
print(f"{len(fallback_missed)} fallback item(s) had usable OFF candidates that scored too low to be chosen:")
fallback_missed[["raw_name", "off_query", "n_candidates_with_nutrition", "alternative_names_with_nutrition"]]

2 fallback item(s) had usable OFF candidates that scored too low to be chosen:

,raw_name,off_query,n_candidates_with_nutrition,alternative_names_with_nutrition
117,"Vollmilch 3,5% 1L",Test Milch,1,[Gouda Jung]
137,"Vollmilch 3,5% 1L","Test Milch 3,5%",1,[Gouda Jung]

In [7]:
fuzzy_with_alts = df[(df["match_type"] != "fallback") & (df["n_alternatives_with_nutrition"] > 0)].sort_values(
    "n_alternatives_with_nutrition", ascending=False
)
print(f"{len(fuzzy_with_alts)} accepted match(es) had at least one unused alternative with nutrition data:")
fuzzy_with_alts[["raw_name", "off_query", "match_type", "matched_name", "confidence",
                 "n_alternatives_with_nutrition", "alternative_names_with_nutrition"]]

137 accepted match(es) had at least one unused alternative with nutrition data:

,raw_name,off_query,match_type,matched_name,confidence,n_alternatives_with_nutrition,alternative_names_with_nutrition
0,RUCOLA,Rucola,fuzzy,Pesto basilic roquette basilicum en rucola,0.850,4,"[Pesto Basilico e Rucula, Pizza Rucola Ristorante, Brotaufstrich pflanzlich ..."
119,Vollkornbrot 500g,Vollkornbrot,exact,Vollkornbrot,1.000,4,"[Pain spécial Vollkornbrot au seigle 500g, Pain noir allemand vollkornbrot 5..."
116,Naturjoghurt 500g,Naturjoghurt,fuzzy,"Joghurt mild 3,5 % Fett",0.850,4,"[Bio Fettarmer Joghurt mild, Cremiger Jogurt - 3,8 % Fett, Joghurt Natur 3,5..."
115,Haferflocken 500g,Haferflocken,exact,Haferflocken,1.000,4,"[Hafer Flocken Zart, Blütenzarte Haferflocken, Zarte Haferflocken, Kernige H..."
114,Gouda jung 200g,Gouda jung,exact,Gouda Jung,1.000,4,"[Gouda jung in Scheiben, Käse Gouda jung, Gouda Jung, Junger Gouda In Scheib..."
113,Bio Eier 10 Stk,Bio Eier,fuzzy,Eier,0.850,4,"[Vegane Salatmayo, Eier, Vegane Mayo, Eier]"
112,"Bananen 1,0 kg",Bananen,fuzzy,Bananenchips,0.850,4,"[Bananen Joghurt mit Knuspermüsli Schoko, Schoko Bananen, Protein Knuspermüs..."
111,Vollkornbrot 500g,Vollkornbrot,exact,Vollkornbrot,1.000,4,"[Pain spécial Vollkornbrot au seigle 500g, Pain noir allemand vollkornbrot 5..."
110,Naturjoghurt 500g,Naturjoghurt,fuzzy,"Joghurt mild 3,5 % Fett",0.850,4,"[Bio Fettarmer Joghurt mild, Cremiger Jogurt - 3,8 % Fett, Joghurt Natur 3,5..."
109,Haferflocken 500g,Haferflocken,exact,Haferflocken,1.000,4,"[Hafer Flocken Zart, Blütenzarte Haferflocken, Zarte Haferflocken, Kernige H..."
108,Gouda jung 200g,Gouda jung,exact,Gouda Jung,1.000,4,"[Gouda jung in Scheiben, Käse Gouda jung, Gouda Jung, Junger Gouda In Scheib..."
107,Bio Eier 10 Stk,Bio Eier,fuzzy,Eier,0.850,4,"[Vegane Salatmayo, Eier, Vegane Mayo, Eier]"
106,"Bananen 1,0 kg",Bananen,fuzzy,Bananenchips,0.850,4,"[Bananen Joghurt mit Knuspermüsli Schoko, Schoko Bananen, Protein Knuspermüs..."
105,Vollkornbrot 500g,Vollkornbrot,exact,Vollkornbrot,1.000,4,"[Pain spécial Vollkornbrot au seigle 500g, Pain noir allemand vollkornbrot 5..."
104,"Vollmilch 3,5% 1L",Vollmilch,exact,Vollmilch,1.000,4,"[H-Milch 3,5%, H-Vollmilch 3,5 % Fett, Haltbare Milch 3,8% Fett, Lebkuchen V..."
103,Naturjoghurt 500g,Naturjoghurt,fuzzy,"Joghurt mild 3,5 % Fett",0.850,4,"[Bio Fettarmer Joghurt mild, Cremiger Jogurt - 3,8 % Fett, Joghurt Natur 3,5..."
102,Haferflocken 500g,Haferflocken,exact,Haferflocken,1.000,4,"[Hafer Flocken Zart, Blütenzarte Haferflocken, Zarte Haferflocken, Kernige H..."
101,Gouda jung 200g,Gouda jung,exact,Gouda Jung,1.000,4,"[Gouda jung in Scheiben, Käse Gouda jung, Gouda Jung, Junger Gouda In Scheib..."
100,Bio Eier 10 Stk,Bio Eier,fuzzy,Eier,0.850,4,"[Vegane Salatmayo, Eier, Vegane Mayo, Eier]"
99,"Bananen 1,0 kg",Bananen,fuzzy,Bananenchips,0.850,4,"[Bananen Joghurt mit Knuspermüsli Schoko, Schoko Bananen, Protein Knuspermüs..."
98,Vollkornbrot 500g,Vollkornbrot,exact,Vollkornbrot,1.000,4,"[Pain spécial Vollkornbrot au seigle 500g, Pain noir allemand vollkornbrot 5..."
97,"Vollmilch 3,5% 1L",Vollmilch,exact,Vollmilch,1.000,4,"[H-Milch 3,5%, H-Vollmilch 3,5 % Fett, Haltbare Milch 3,8% Fett, Lebkuchen V..."
96,Naturjoghurt 500g,Naturjoghurt,fuzzy,"Joghurt mild 3,5 % Fett",0.850,4,"[Bio Fettarmer Joghurt mild, Cremiger Jogurt - 3,8 % Fett, Joghurt Natur 3,5..."
95,Haferflocken 500g,Haferflocken,exact,Haferflocken,1.000,4,"[Hafer Flocken Zart, Blütenzarte Haferflocken, Zarte Haferflocken, Kernige H..."
94,Gouda jung 200g,Gouda jung,exact,Gouda Jung,1.000,4,"[Gouda jung in Scheiben, Käse Gouda jung, Gouda Jung, Junger Gouda In Scheib..."
93,Bio Eier 10 Stk,Bio Eier,fuzzy,Eier,0.850,4,"[Vegane Salatmayo, Eier, Vegane Mayo, Eier]"
92,"Bananen 1,0 kg",Bananen,fuzzy,Bananenchips,0.850,4,"[Bananen Joghurt mit Knuspermüsli Schoko, Schoko Bananen, Protein Knuspermüs..."
91,Vollkornbrot 500g,Vollkornbrot,exact,Vollkornbrot,1.000,4,"[Pain spécial Vollkornbrot au seigle 500g, Pain noir allemand vollkornbrot 5..."
90,"Vollmilch 3,5% 1L","Vollmilch 3,5%",fuzzy,"H-Milch 3,5%",0.850,4,"[H-Vollmilch 3,5 % Fett, Haltbare Milch 3,8% Fett, Lebkuchen Vollmilch, Voll..."
89,Naturjoghurt 500g,Naturjoghurt,fuzzy,"Joghurt mild 3,5 % Fett",0.850,4,"[Bio Fettarmer Joghurt mild, Cremiger Jogurt - 3,8 % Fett, Joghurt Natur 3,5..."
88,Haferflocken 500g,Haferflocken,exact,Haferflocken,1.000,4,"[Hafer Flocken Zart, Blütenzarte Haferflocken, Zarte Haferflocken, Kernige H..."
118,"Vollmilch 3,5% 1L",Vollmilch,exact,Vollmilch,1.000,4,"[H-Milch 3,5%, H-Vollmilch 3,5 % Fett, Haltbare Milch 3,8% Fett, Lebkuchen V..."
120,"Bananen 1,0 kg",Bananen,fuzzy,Bananenchips,0.850,4,"[Bananen Joghurt mit Knuspermüsli Schoko, Schoko Bananen, Protein Knuspermüs..."
85,"Bananen 1,0 kg",Bananen,fuzzy,Bananenchips,0.850,4,"[Bananen Joghurt mit Knuspermüsli Schoko, Schoko Bananen, Protein Knuspermüs..."
121,Bio Eier 10 Stk,Bio Eier,fuzzy,Eier,0.850,4,"[Vegane Salatmayo, Eier, Vegane Mayo, Eier]"
163,"SB JB-Roastbeef ca.280gQS kg 0,294",Roastbeef,exact,Roastbeef,1.000,4,"[Natural hazelnuts, På lækker Roastbeef, Baguette au roastbeef nature, Roast..."
162,Avocado vorgereift ST,avocado,fuzzy,Avocados,0.700,4,"[Avocado Oil Spray, All Natural Avocado Oil Mayo, MAYO Real Mayonnaise made ..."
158,Vollmilch,Vollmilch,exact,Vollmilch,1.000,4,"[H-Milch 3,5%, H-Vollmilch 3,5 % Fett, Haltbare Milch 3,8% Fett, Lebkuchen V..."
157,Linsen,Linsen,fuzzy,DM Bio Linsenwaffeln 100g 1.35€ 1kg 13.50€,0.850,4,"[Linsen Chips Paprika Style, Linsen Waffeln, Linsen Chips Sour Creme Style, ..."
156,Weissbrot,Weissbrot,exact,Weissbrot,1.000,4,"[Weissbrot, Weissbrot, Anker Weißbrot, Brot, Weissbrot]"
155,Vollmilch,Vollmilch,exact,Vollmilch,1.000,4,"[H-Milch 3,5%, H-Vollmilch 3,5 % Fett, Haltbare Milch 3,8% Fett, Lebkuchen V..."
154,Rote Linsen,Rote Linsen,fuzzy,Rote Linsen Bratlinge,0.850,4,"[Fusilli Rote Linsen, Rote Linsen, getrocknet, Rote Linsen Spirelli, Rote Li..."
153,Weissbrot,Weissbrot,exact,Weissbrot,1.000,4,"[Weissbrot, Weissbrot, Anker Weißbrot, Brot, Weissbrot]"
152,Vollmilch,Vollmilch,exact,Vollmilch,1.000,4,"[H-Milch 3,5%, H-Vollmilch 3,5 % Fett, Haltbare Milch 3,8% Fett, Lebkuchen V..."
149,"COCA COLA 1,25L",Coca Cola,exact,Coca Cola,1.000,4,"[Coca-Cola Original Taste, Hawai Tropical, Coca Cola, PET 1.75L COCA]"
147,BANAN LOSE,Bananen,fuzzy,Bananenchips,0.850,4,"[Bananen Joghurt mit Knuspermüsli Schoko, Schoko Bananen, Protein Knuspermüs..."
146,VK BROT KOERN,Vollkornbrot,exact,Vollkornbrot,1.000,4,"[Pain spécial Vollkornbrot au seigle 500g, Pain noir allemand vollkornbrot 5..."
144,Naturjoghurt 500g,Naturjoghurt,fuzzy,"Joghurt mild 3,5 % Fett",0.850,4,"[Bio Fettarmer Joghurt mild, Cremiger Jogurt - 3,8 % Fett, Joghurt Natur 3,5..."
143,Haferflocken 500g,Haferflocken,exact,Haferflocken,1.000,4,"[Hafer Flocken Zart, Blütenzarte Haferflocken, Zarte Haferflocken, Kernige H..."
142,Gouda jung 200g,Gouda jung,exact,Gouda Jung,1.000,4,"[Gouda jung in Scheiben, Käse Gouda jung, Gouda Jung, Junger Gouda In Scheib..."
141,Bio Eier 10 Stk,Bio Eier,fuzzy,Eier,0.850,4,"[Vegane Salatmayo, Eier, Vegane Mayo, Eier]"
140,"Bananen 1,0 kg",Bananen,fuzzy,Bananenchips,0.850,4,"[Bananen Joghurt mit Knuspermüsli Schoko, Schoko Bananen, Protein Knuspermüs..."
139,Vollkornbrot 500g,Vollkornbrot,exact,Vollkornbrot,1.000,4,"[Pain spécial Vollkornbrot au seigle 500g, Pain noir allemand vollkornbrot 5..."
138,"Vollmilch 3,5% 1L",Vollmilch,exact,Vollmilch,1.000,4,"[H-Milch 3,5%, H-Vollmilch 3,5 % Fett, Haltbare Milch 3,8% Fett, Lebkuchen V..."
136,Naturjoghurt 500g,Naturjoghurt,fuzzy,"Joghurt mild 3,5 % Fett",0.850,4,"[Bio Fettarmer Joghurt mild, Cremiger Jogurt - 3,8 % Fett, Joghurt Natur 3,5..."
135,Haferflocken 500g,Haferflocken,exact,Haferflocken,1.000,4,"[Hafer Flocken Zart, Blütenzarte Haferflocken, Zarte Haferflocken, Kernige H..."
134,Gouda jung 200g,Gouda jung,exact,Gouda Jung,1.000,4,"[Gouda jung in Scheiben, Käse Gouda jung, Gouda Jung, Junger Gouda In Scheib..."
133,Bio Eier 10 Stk,Bio Eier,fuzzy,Eier,0.850,4,"[Vegane Salatmayo, Eier, Vegane Mayo, Eier]"
132,"Bananen 1,0 kg",Bananen,fuzzy,Bananenchips,0.850,4,"[Bananen Joghurt mit Knuspermüsli Schoko, Schoko Bananen, Protein Knuspermüs..."
131,Vollkornbrot 500g,Vollkornbrot,exact,Vollkornbrot,1.000,4,"[Pain spécial Vollkornbrot au seigle 500g, Pain noir allemand vollkornbrot 5..."
130,LAUCHZWIEBELN,Zwiebel,fuzzy,Bio Zwiebel & Knoblauch Gehackte Tomaten,0.850,4,"[Kartoffelsalat Gurke, Zwiebel & Ei, Bio-Brotaufstrich - Zwiebel und Apfel, ..."
124,Naturjoghurt 500g,Naturjoghurt,fuzzy,"Joghurt mild 3,5 % Fett",0.850,4,"[Bio Fettarmer Joghurt mild, Cremiger Jogurt - 3,8 % Fett, Joghurt Natur 3,5..."
123,Haferflocken 500g,Haferflocken,exact,Haferflocken,1.000,4,"[Hafer Flocken Zart, Blütenzarte Haferflocken, Zarte Haferflocken, Kernige H..."
122,Gouda jung 200g,Gouda jung,exact,Gouda Jung,1.000,4,"[Gouda jung in Scheiben, Käse Gouda jung, Gouda Jung, Junger Gouda In Scheib..."
86,Bio Eier 10 Stk,Bio Eier,fuzzy,Eier,0.850,4,"[Vegane Salatmayo, Eier, Vegane Mayo, Eier]"
87,Gouda jung 200g,Gouda jung,exact,Gouda Jung,1.000,4,"[Gouda jung in Scheiben, Käse Gouda jung, Gouda Jung, Junger Gouda In Scheib..."
84,Vollkornbrot 500g,Vollkornbrot,exact,Vollkornbrot,1.000,4,"[Pain spécial Vollkornbrot au seigle 500g, Pain noir allemand vollkornbrot 5..."
47,rote linsen,Rote Linsen,fuzzy,Rote Linsen Bratlinge,0.850,4,"[Fusilli Rote Linsen, Rote Linsen, getrocknet, Rote Linsen Spirelli, Rote Li..."
83,"Vollmilch 3,5% 1L",Vollmilch,exact,Vollmilch,1.000,4,"[H-Milch 3,5%, H-Vollmilch 3,5 % Fett, Haltbare Milch 3,8% Fett, Lebkuchen V..."
43,LINSEN MIT SG,Linsen,fuzzy,DM Bio Linsenwaffeln 100g 1.35€ 1kg 13.50€,0.850,4,"[Linsen Chips Paprika Style, Linsen Waffeln, Linsen Chips Sour Creme Style, ..."
42,Gurken Stück x,Gurken,exact,Gurken,1.000,4,"[Cornichons Gurken, Gewürzgurken, KNAX Gewürzgurken, Snack-Gurken]"
41,Cocktailrispe,tomate,fuzzy,Tomato-Ketchup,0.700,4,"[sauce tomate cuisinée, Basilico, Chips de lentilles saveur tomate mozza, Le..."
37,"SB JB-Roastbeef ca.280gQS kg 0,294",Roastbeef,exact,Roastbeef,1.000,4,"[Natural hazelnuts, På lækker Roastbeef, Baguette au roastbeef nature, Roast..."
36,Avocado vorgereift ST,avocado,fuzzy,Avocados,0.700,4,"[Avocado Oil Spray, All Natural Avocado Oil Mayo, MAYO Real Mayonnaise made ..."
32,"Vollmilch 3,5% 1L",Bio Vollmilch,exact,Haltbare Bio Vollmilch,1.000,4,"[Bio Vollmilch, Vollmilch Schoko Reiswaffeln Bio, ALDI BIO Frische Bio-Vollm..."
31,Naturjoghurt 500g,Naturjoghurt,fuzzy,"Joghurt mild 3,5 % Fett",0.850,4,"[Bio Fettarmer Joghurt mild, Cremiger Jogurt - 3,8 % Fett, Joghurt Natur 3,5..."
30,Haferflocken 500g,Haferflocken,exact,Haferflocken,1.000,4,"[Hafer Flocken Zart, Blütenzarte Haferflocken, Zarte Haferflocken, Kernige H..."
29,Gouda jung 200g,Gouda jung,exact,Gouda Jung,1.000,4,"[Gouda jung in Scheiben, Käse Gouda jung, Gouda Jung, Junger Gouda In Scheib..."
28,Bio Eier 10 Stk,Bio Eier,fuzzy,Eier,0.850,4,"[Vegane Salatmayo, Eier, Vegane Mayo, Eier]"
27,"Bananen 1,0 kg",Bananen,fuzzy,Bananenchips,0.850,4,"[Bananen Joghurt mit Knuspermüsli Schoko, Schoko Bananen, Protein Knuspermüs..."
26,Vollkornbrot 500g,Vollkornbrot,exact,Vollkornbrot,1.000,4,"[Pain spécial Vollkornbrot au seigle 500g, Pain noir allemand vollkornbrot 5..."
24,Naturjoghurt 500g,Naturjoghurt,fuzzy,"Joghurt mild 3,5 % Fett",0.850,4,"[Bio Fettarmer Joghurt mild, Cremiger Jogurt - 3,8 % Fett, Joghurt Natur 3,5..."
23,Haferflocken 500g,Haferflocken,exact,Haferflocken,1.000,4,"[Hafer Flocken Zart, Blütenzarte Haferflocken, Zarte Haferflocken, Kernige H..."
22,Gouda jung 200g,Gouda jung,exact,Gouda Jung,1.000,4,"[Gouda jung in Scheiben, Käse Gouda jung, Gouda Jung, Junger Gouda In Scheib..."
21,Bio Eier 10 Stk,Bio Eier,fuzzy,Eier,0.850,4,"[Vegane Salatmayo, Eier, Vegane Mayo, Eier]"
20,"Bananen 1,0 kg",Bananen,fuzzy,Bananenchips,0.850,4,"[Bananen Joghurt mit Knuspermüsli Schoko, Schoko Bananen, Protein Knuspermüs..."
19,Vollkornbrot 500g,Vollkornbrot,exact,Vollkornbrot,1.000,4,"[Pain spécial Vollkornbrot au seigle 500g, Pain noir allemand vollkornbrot 5..."
18,"Vollmilch 3,5% 1L","Vollmilch 3,5%",fuzzy,"H-Milch 3,5%",0.850,4,"[H-Vollmilch 3,5 % Fett, Haltbare Milch 3,8% Fett, Lebkuchen Vollmilch, Voll..."
13,G&G Tomaten g,tomate,fuzzy,Tomato-Ketchup,0.700,4,"[sauce tomate cuisinée, Basilico, Chips de lentilles saveur tomate mozza, Le..."
10,SPAN. GRÜNE/GESCHW.OLI,Spanische Oliven,exact,Spanische Oliven,1.000,4,"[Spanische grüne Oliven mit Stein, Spanische Grüne Manzanilla-Oliven, entste..."
9,HIRTENKÄSE,Hirtenkäse,fuzzy,High Protein Hirtenkäse Jalapeno,0.850,4,"[High Protein Hirtenkäse, Hirtenkäse traditionell (Gazi), Hirtenkäse Traditi..."
8,REISNUDELN 200G,Reisnudeln,exact,Reisnudeln,1.000,4,"[Nudeln-Reisnudeln Pad Thai, Gua Thai Reisnudeln, Nudeln aus Naturreis, Nudeln]"
7,PAPRIKA MIX,Paprika Mix,exact,Chilli & paprika mix,1.000,4,[Crevettes purée de patate douce au paprika fumé légumes verts sauce chimich...
6,FLAMMKUCHENTEIG,Flammkuchenteig,exact,Flammkuchenteig,1.000,4,"[Frischer Flammkuchenteig, Flammkuchenteig Dinkel, Flammkuchenteig auf Backp..."
5,KOKOSNUSSMILCH,Kokosnussmilch,exact,Kokosnussmilch,1.000,4,"[Kokosnussmilch Klassik, kokosnuss milch, Kokosnussmilch cremig, Kokosnussmi..."
46,"vollmilch 0,5l",Vollmilch,exact,Vollmilch,1.000,4,"[H-Milch 3,5%, H-Vollmilch 3,5 % Fett, Haltbare Milch 3,8% Fett, Lebkuchen V..."
44,apfel x 3,Äpfel,fuzzy,c.m. plus Knusper-Müesli Äpfel & Honig,0.850,4,"[Vegane Pommersche Apfel und Zwieben, Himbeere Apfel, Apfel naturtrüb Direkt..."
67,Naturjoghurt 500g,Naturjoghurt,fuzzy,"Joghurt mild 3,5 % Fett",0.850,4,"[Bio Fettarmer Joghurt mild, Cremiger Jogurt - 3,8 % Fett, Joghurt Natur 3,5..."
63,"Bananen 1,0 kg",Bananen,fuzzy,Bananenchips,0.850,4,"[Bananen Joghurt mit Knuspermüsli Schoko, Schoko Bananen, Protein Knuspermüs..."
82,Schokolade 3kg,Schokolade,fuzzy,Dunkle Schokolade mit ganzen Haselnüssen,0.850,4,"[Toffifee 15er, Sweet & saltynut, Haselnuss Schokolade, Toffifee weiße Schok..."
81,SPAN. GRÜNE/GESCHW.OLI,Spanische Oliven,exact,Spanische Oliven,1.000,4,"[Spanische grüne Oliven mit Stein, Spanische Grüne Manzanilla-Oliven, entste..."
80,HIRTENKÄSE,Hirtenkäse,fuzzy,High Protein Hirtenkäse Jalapeno,0.850,4,"[High Protein Hirtenkäse, Hirtenkäse traditionell (Gazi), Hirtenkäse Traditi..."
79,REISNUDELN 200G,Reisnudeln,exact,Reisnudeln,1.000,4,"[Nudeln-Reisnudeln Pad Thai, Gua Thai Reisnudeln, Nudeln aus Naturreis, Nudeln]"
78,PAPRIKA MIX,Paprika Mix,exact,Chilli & paprika mix,1.000,4,[Crevettes purée de patate douce au paprika fumé légumes verts sauce chimich...
77,FLAMMKUCHENTEIG,Flammkuchenteig,exact,Flammkuchenteig,1.000,4,"[Frischer Flammkuchenteig, Flammkuchenteig Dinkel, Flammkuchenteig auf Backp..."
76,KOKOSNUSSMILCH,Kokosnussmilch,exact,Kokosnussmilch,1.000,4,"[Kokosnussmilch Klassik, kokosnuss milch, Kokosnussmilch cremig, Kokosnussmi..."
71,RUCOLA,Rucola,fuzzy,Pesto basilic roquette basilicum en rucola,0.850,4,"[Pesto Basilico e Rucula, Pizza Rucola Ristorante, Brotaufstrich pflanzlich ..."
69,TK DR. OETKER OFENFR.,Dr. Oetker Ofenfrische Pizza,fuzzy,Die Ofenfrische Margherita,0.850,4,"[Die Ofenfrische Thunfisch, Die Ofenfrische Speciale, Pizza Salami Die Ofenf..."
68,ÖSTERREICHISCHER BERGK,Österreichischer Bergkäse,exact,Österreichischer Bergkäse,1.000,4,"[Original österreichischer Bergkäse, Österreichischer Bergkäse, 45 % Fett i...."
66,Haferflocken 500g,Haferflocken,exact,Haferflocken,1.000,4,"[Hafer Flocken Zart, Blütenzarte Haferflocken, Zarte Haferflocken, Kernige H..."
65,Gouda jung 200g,Gouda jung,exact,Gouda Jung,1.000,4,"[Gouda jung in Scheiben, Käse Gouda jung, Gouda Jung, Junger Gouda In Scheib..."
64,Bio Eier 10 Stk,Bio Eier,fuzzy,Eier,0.850,4,"[Vegane Salatmayo, Eier, Vegane Mayo, Eier]"
165,LINSEN MIT SG,Linsen,fuzzy,DM Bio Linsenwaffeln 100g 1.35€ 1kg 13.50€,0.850,4,"[Linsen Chips Paprika Style, Linsen Waffeln, Linsen Chips Sour Creme Style, ..."
62,Vollkornbrot 500g,Vollkornbrot,exact,Vollkornbrot,1.000,4,"[Pain spécial Vollkornbrot au seigle 500g, Pain noir allemand vollkornbrot 5..."
61,"Vollmilch 3,5% 1L",Vollmilch,exact,Vollmilch,1.000,4,"[H-Milch 3,5%, H-Vollmilch 3,5 % Fett, Haltbare Milch 3,8% Fett, Lebkuchen V..."
60,Naturjoghurt 500g,Naturjoghurt,fuzzy,"Joghurt mild 3,5 % Fett",0.850,4,"[Bio Fettarmer Joghurt mild, Cremiger Jogurt - 3,8 % Fett, Joghurt Natur 3,5..."
59,Haferflocken 500g,Haferflocken,exact,Haferflocken,1.000,4,"[Hafer Flocken Zart, Blütenzarte Haferflocken, Zarte Haferflocken, Kernige H..."
54,"Vollmilch 3,5% 1L",Vollmilch,exact,Vollmilch,1.000,4,"[H-Milch 3,5%, H-Vollmilch 3,5 % Fett, Haltbare Milch 3,8% Fett, Lebkuchen V..."
55,Vollkornbrot 500g,Vollkornbrot,exact,Vollkornbrot,1.000,4,"[Pain spécial Vollkornbrot au seigle 500g, Pain noir allemand vollkornbrot 5..."
56,"Bananen 1,0 kg",Bananen,fuzzy,Bananenchips,0.850,4,"[Bananen Joghurt mit Knuspermüsli Schoko, Schoko Bananen, Protein Knuspermüs..."
57,Bio Eier 10 Stk,Bio Eier,fuzzy,Eier,0.850,4,"[Vegane Salatmayo, Eier, Vegane Mayo, Eier]"
58,Gouda jung 200g,Gouda jung,exact,Gouda Jung,1.000,4,"[Gouda jung in Scheiben, Käse Gouda jung, Gouda Jung, Junger Gouda In Scheib..."
2,LAUCHZWIEBELN,Lauchzwiebeln,fuzzy,"Couscoussalat mit Paprika, Salzlakenkäse und Lauchzwiebeln",0.850,3,"[Obazda Lauchzwiebeln, Bulgursalat mit Lauchzwiebeln und Gemüse, Bulgursalat..."
161,"Suesskartoffeln 0,718 kg",Süßkartoffeln,fuzzy,Red lentil & sweet potato noodles | Fusilli aus roten Linsen und Süsskartoffeln,0.889,3,"[Nudeln Aus Süßkartoffeln - Hosaku - 500G, Gemüse mit Süßkartoffeln und Huhn..."
45,hackfleisch 400g,Hackfleisch,fuzzy,Veganes Mühlen Hack,0.850,3,[Puten-Hackfleisch Frisch; gewürzt; zum Braten Aus der Frischetruhe Dauerti...
48,LAUCHZWIEBELN,Lauchzwiebeln,fuzzy,"Couscoussalat mit Paprika, Salzlakenkäse und Lauchzwiebeln",0.850,3,"[Obazda Lauchzwiebeln, Bulgursalat mit Lauchzwiebeln und Gemüse, Bulgursalat..."
73,LAUCHZWIEBELN,Lauchzwiebeln,fuzzy,"Couscoussalat mit Paprika, Salzlakenkäse und Lauchzwiebeln",0.850,3,"[Obazda Lauchzwiebeln, Bulgursalat mit Lauchzwiebeln und Gemüse, Bulgursalat..."
70,BIO OLIVENÖL,Bio Olivenöl,exact,Bio Olivenöl Nativ Extra,1.000,3,"[Olivenöl nativ extra, Italienisches Olivenöl, Bio olivenöl]"
35,"Suesskartoffeln 0,718 kg",Süßkartoffeln,fuzzy,Red lentil & sweet potato noodles | Fusilli aus roten Linsen und Süsskartoffeln,0.889,3,"[Nudeln Aus Süßkartoffeln - Hosaku - 500G, Gemüse mit Süßkartoffeln und Huhn..."
148,"H-MILCH 1,5% 6X1L",H-Milch 1.5%,fuzzy,Fettarme H-Milch ultrahocherhitzt homogenisiert 1.5% Fett LAKTOSEFREI,0.850,2,"[H-Milch 1.5% Fett laktosefrei, Mleko UHT 1.5%]"
145,MILCH FRISCH 3.5%,Frische Milch 3.5%,fuzzy,Bergbauern Milch,0.850,2,"[Weihenstephan Milch 3.5%, Frische Vollmilch 3.5% fett]"
40,PORREE,Porree,fuzzy,Porree Rahm-Gemüse,0.850,2,"[Wrap - Hähnchen Teriyaki, Porree Paste]"
3,KOHLRABI,Kohlrabi,fuzzy,Kohlrabi G-Rahm-Gemüse,0.850,2,"[Superfood brussels sprouts, napa cabbage, kohlrabi, broccoli, carrots & kal..."
74,KOHLRABI,Kohlrabi,fuzzy,Kohlrabi G-Rahm-Gemüse,0.850,2,"[Superfood brussels sprouts, napa cabbage, kohlrabi, broccoli, carrots & kal..."
126,FELDSALAT,Feldsalat,exact,Feldsalat,1.000,1,[Bio Feldsalat]
127,CHAMPIGNONS GROSS,Champignons Groß,fuzzy,Champignons,0.850,1,[Truffes]
50,FELDSALAT,Feldsalat,exact,Feldsalat,1.000,1,[Bio Feldsalat]

## Export (optional)

Writes the full table next to this notebook for offline review / sharing. Not required to run — everything above already displays inline.

In [ ]:
out_path = Path("matching_investigation_results.csv")
df.to_csv(out_path, index=False)
print(f"Saved {len(df)} rows to {out_path.resolve()}")