# Receipt item extraction — raw pull

Runs the **real, current extraction pipeline** (`backend/app/services/local_extractor.extract_text` + `backend/app/services/receipt_text_parser.parse_receipt_text_offline` — nothing reimplemented) over every file in `receipts/`, and collects the same data the API normally writes to Supabase's `receipts` + `receipt_items` tables (see `backend/app/api/receipts.py`, `backend/app/db/receipt_items_repo.py`).

**Deliberately out of scope here:** no OpenFoodFacts / BLS matching, no fallback-category-based nutrition estimate (that's `services/fallback_categories.py`, called from the `/receipts/{id}/mapping` endpoint — a separate step). The offline text parser does compute a coarse `category` per item internally (its own static keyword guess, used later as a fallback-matching input) — we deliberately **drop that field** from the collected dataset below so this notebook stays a pure extraction pull.

Nothing here writes to Supabase or any network service — everything runs local (Tesseract OCR + PyMuPDF), same as the app's own receipt pipeline.

In [1]:
import sys
from pathlib import Path

# Make sure `backend` is importable regardless of where Jupyter's cwd ends up.
_here = Path.cwd()
for _candidate in [_here, *_here.parents]:
    if (_candidate / "backend").is_dir():
        if str(_candidate) not in sys.path:
            sys.path.insert(0, str(_candidate))
        REPO_ROOT = _candidate
        break
else:
    raise RuntimeError("Could not find the repo root (a parent containing 'backend/') from cwd=" + str(_here))

import mimetypes
from uuid import uuid4

import pandas as pd

from backend.app.services import local_extractor
from backend.app.services.receipt_text_parser import parse_receipt_text_offline

pd.set_option("display.max_colwidth", 80)
pd.set_option("display.max_rows", 300)

RECEIPTS_DIR = REPO_ROOT / "receipts"
REPO_ROOT, RECEIPTS_DIR

(PosixPath('/Users/stuartkasemeier/Documents/Work/07-Arbeitslosigkeit/ai_project_management/neuefische_course/AIPM_capstone_project_supermarket_optimizer'),
 PosixPath('/Users/stuartkasemeier/Documents/Work/07-Arbeitslosigkeit/ai_project_management/neuefische_course/AIPM_capstone_project_supermarket_optimizer/receipts'))

## Discover receipt files

Every file directly inside `receipts/` (PDFs and phone-photo images — jpg/jpeg/png/etc), sorted for a stable run order.

In [2]:
receipt_files = sorted(p for p in RECEIPTS_DIR.iterdir() if p.is_file() and not p.name.startswith("."))
print(f"{len(receipt_files)} receipt files found")
for p in receipt_files:
    print(" -", p.name)

21 receipt files found
 - 2026.06.30_23001961862026063034796.jpg.png
 - IMG_1928.JPG
 - IMG_1929.JPG
 - IMG_1930.JPG
 - IMG_1931.JPG
 - IMG_1932.JPG
 - IMG_1933.JPG
 - IMG_1934.JPG
 - IMG_1936.JPG
 - IMG_1937.PNG
 - Netto_Kassenbon_20260702-191137.pdf
 - Netto_Kassenbon_20260707-180115.pdf
 - Netto_Kassenbon_20260709-172131.pdf
 - Netto_Kassenbon_20260713-170620.pdf
 - Netto_Kassenbon_20260714-133412.pdf
 - Netto_Kassenbon_20260716-095742.pdf
 - WhatsApp Image 2026-07-05 at 11.02.48.jpeg
 - WhatsApp Image 2026-07-16 at 13.05.02.jpeg
 - WhatsApp Image 2026-07-16 at 13.05.29.jpeg
 - WhatsApp Image 2026-07-16 at 13.05.48.jpeg
 - WhatsApp Image 2026-07-16 at 13.07.58.jpeg

## Extraction

For each file: `local_extractor.extract_text` (PyMuPDF text layer for PDFs, Tesseract OCR for images) -> `parse_receipt_text_offline` (store/date detection + line-item parsing). Mirrors `receipt_parser.scan_receipt_bytes` minus the mock-mode branch, since we want the real extractor to actually run on every file.

One `receipts`-shaped record per file, one `receipt_items`-shaped record per parsed line item (joined by a locally-generated `receipt_id`, same as `upload_receipt` does with `uuid4()`).

In [3]:
receipts_rows = []
items_rows = []

for path in receipt_files:
    receipt_id = str(uuid4())
    file_bytes = path.read_bytes()
    file_type = mimetypes.guess_type(path.name)[0]

    receipt_row = {
        "receipt_id": receipt_id,
        "file_name": path.name,
        "file_type": file_type,
        "status": None,
        "store": None,
        "purchase_date": None,
        "scan_quality": None,
        "items_count": 0,
        "non_food_items_ignored_count": 0,
        "error": None,
    }

    try:
        raw_text = local_extractor.extract_text(file_bytes, path.name)
        parsed = parse_receipt_text_offline(raw_text)

        receipt_row["status"] = "processed"
        receipt_row["store"] = parsed.get("store")
        receipt_row["purchase_date"] = parsed.get("date")
        receipt_row["scan_quality"] = parsed.get("scan_quality")
        receipt_row["items_count"] = parsed.get("items_count", 0)
        receipt_row["non_food_items_ignored_count"] = len(parsed.get("non_food_items_ignored", []) or [])

        for item in parsed.get("items", []) or []:
            items_rows.append({
                "item_id": str(uuid4()),
                "receipt_id": receipt_id,
                "file_name": path.name,

                # Core NLP outputs (receipt_items.raw_name / normalized_name)
                "raw_name": item.get("original_text") or item.get("name"),
                "normalized_name": item.get("name"),

                # Quantitative data
                "quantity": item.get("quantity"),
                "unit": item.get("unit"),
                "price": item.get("price"),

                # NOTE: no "category" here on purpose — that's the fallback-
                # category step (services/fallback_categories.py), out of
                # scope for this raw-extraction pull.
                "matched_product_id": None,  # OFF/BLS matching not run here

                # Confidence signal — identical rule to receipt_items_repo.insert_receipt_items
                "confidence": 0.5 if item.get("uncertain") else 0.9,
                "uncertain": item.get("uncertain"),
            })

    except local_extractor.UnreadableReceipt as e:
        receipt_row["status"] = "error"
        receipt_row["error"] = str(e)

    receipts_rows.append(receipt_row)

print(f"{len(receipts_rows)} receipts processed, {len(items_rows)} items extracted")
print(f"{sum(1 for r in receipts_rows if r['status'] == 'error')} receipt(s) failed to extract")

21 receipts processed, 119 items extracted
0 receipt(s) failed to extract

## Results

`df_receipts` mirrors the `receipts` table (one row per file); `df_items` mirrors `receipt_items` (one row per parsed line item).

In [4]:
df_receipts = pd.DataFrame(receipts_rows)
df_receipts

,receipt_id,file_name,file_type,status,store,purchase_date,scan_quality,items_count,non_food_items_ignored_count,error
0,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,image/png,processed,Lidl,2026-06-30,good,15,3,None
1,8d554238-2f93-4096-9d0c-e0a516bcda25,IMG_1928.JPG,image/jpeg,processed,Netto,2026-06-17,good,2,0,None
2,30bb7241-c4aa-4d61-ba68-9eeffa94c335,IMG_1929.JPG,image/jpeg,processed,Edeka,NaN,good,8,1,None
3,7f34b522-89f4-46ef-a383-ac477898223c,IMG_1930.JPG,image/jpeg,processed,unknown,NaN,poor,0,0,None
4,88607fdc-8c57-41dd-a442-4a816eb4a99c,IMG_1931.JPG,image/jpeg,processed,unknown,NaN,poor,0,0,None
5,ccaa60fc-a78b-4a83-8275-30fe96a0772f,IMG_1932.JPG,image/jpeg,processed,unknown,NaN,poor,0,0,None
6,e2f9af20-46d7-4075-a3c2-627d17dbdba1,IMG_1933.JPG,image/jpeg,processed,unknown,NaN,poor,0,0,None
7,41101fe2-bb90-43d7-abad-c8853c666c5a,IMG_1934.JPG,image/jpeg,processed,unknown,NaN,poor,0,0,None
8,1c0e4ee0-1ddd-43b3-a15a-2a0ce3dc0908,IMG_1936.JPG,image/jpeg,processed,unknown,NaN,poor,0,0,None
9,0c84d1cd-e2b1-4873-af7a-31d06e600720,IMG_1937.PNG,image/png,processed,Kaufland,2026-06-15,good,1,0,None
10,b8398cde-f425-4a5c-985f-7f40f2c6276e,Netto_Kassenbon_20260702-191137.pdf,application/pdf,processed,Netto,2026-07-02,good,4,1,None
11,cc8c3543-623d-4ff6-ae83-a22028742571,Netto_Kassenbon_20260707-180115.pdf,application/pdf,processed,Netto,2026-07-07,good,10,0,None
12,34440959-7870-49fe-85cd-7a227d4cbb39,Netto_Kassenbon_20260709-172131.pdf,application/pdf,processed,Netto,2026-07-09,good,5,0,None
13,4e42fe7b-680a-4843-9139-e92784c3cc31,Netto_Kassenbon_20260713-170620.pdf,application/pdf,processed,Netto,2026-07-13,good,12,0,None
14,93fe7ca9-440a-448a-ab79-0d6024d6b114,Netto_Kassenbon_20260714-133412.pdf,application/pdf,processed,Netto,2026-07-14,good,5,0,None
15,33275a24-9b52-4be6-b4aa-24302b613a7e,Netto_Kassenbon_20260716-095742.pdf,application/pdf,processed,Netto,2026-07-16,good,3,0,None
16,1cc77841-5cc2-42fb-a4b4-dce2cbfa7dfe,WhatsApp Image 2026-07-05 at 11.02.48.jpeg,image/jpeg,processed,unknown,NaN,good,1,0,None
17,c1b9409e-6f60-423d-9495-5a5339261809,WhatsApp Image 2026-07-16 at 13.05.02.jpeg,image/jpeg,processed,Lidl,2026-07-15,good,3,1,None
18,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,image/jpeg,processed,Lidl,2025-12-30,good,26,5,None
19,f0047fbc-d166-45a8-bd62-5e38eba44e23,WhatsApp Image 2026-07-16 at 13.05.48.jpeg,image/jpeg,processed,Lidl,2025-12-10,good,22,2,None
20,98fa427b-99a2-47b7-b4e3-e6d5febbf36e,WhatsApp Image 2026-07-16 at 13.07.58.jpeg,image/jpeg,processed,Rewe,2026-07-15,good,2,0,None

In [5]:
df_items = pd.DataFrame(items_rows)
df_items

,item_id,receipt_id,file_name,raw_name,normalized_name,quantity,unit,price,matched_product_id,confidence,uncertain
0,1827153b-b012-453b-926f-c3df158cae91,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Banane Fair Bio 2,35 A",Banane Fair Bio,1.182,kg,2.35,None,0.5,True
1,592f30db-ea4d-4418-a314-b03d96f7a074,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Zwiebeln weiß 1,28 A",Zwiebeln weiß,0.356,kg,1.28,None,0.5,True
2,97af5108-17a5-480b-af76-e0f0b2e841f3,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Bioland Zucchini 1,49 A",Bioland Zucchini,1.000,piece,1.49,None,0.5,True
3,c3138c2f-675b-4c0d-9b6b-37c3472fcd15,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Petersilie 1,39 A",Petersilie,1.000,piece,1.39,None,0.5,True
4,517fc874-ad36-4723-9408-0ba10f7861d5,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Bio Limetten 1,99 A",Bio Limetten,1.000,piece,1.99,None,0.5,True
5,c9574418-4e27-40cd-b21c-4fab8a121b8b,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Weidemilch 3,8% 1,19 A",Weidemilch,1.000,piece,1.19,None,0.5,True
6,5cc0d5e7-9b8b-483e-a5c4-0159e175d6a9,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Exquisa fitlineNatur 1,59 A",Exquisa fitlineNatur,1.000,piece,1.59,None,0.5,True
7,6bf23279-4d79-4a28-a525-71f9f4ee9f2c,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Bio-Eier OKT 10er 3,99 A",Bio-Eier OKT 10er,1.000,piece,3.99,None,0.5,True
8,1edac537-14b2-4b64-a470-76646701ce9e,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Bio Müsli Schoko Kn. 2,65 A",Bio Müsli Schoko Kn,1.000,piece,2.65,None,0.5,True
9,cd8d9096-6e3c-420a-b96e-c2e89daa45c6,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Lava Bar Cookie 1,69 A",Lava Bar Cookie,1.000,piece,1.69,None,0.5,True
10,9ea14ff0-24a4-4c65-ad0c-37256157f77e,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Dinkelschnitte 1,29 A",Dinkelschnitte,1.000,piece,1.29,None,0.5,True
11,e93b8d45-287f-4410-a47f-e67a3d2d9a7b,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Walnusskerne 2,99 A",Walnusskerne,1.000,piece,2.99,None,0.5,True
12,80f8e9ca-c1bd-44f9-b400-db164f8495af,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Bio Cashewkerne 2,45 A",Bio Cashewkerne,1.000,piece,2.45,None,0.5,True
13,cf4cd0f6-9400-48c4-acd2-a4e4484b7648,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Rinderhackfleisch 5% 5,99 A",Rinderhackfleisch,1.000,piece,5.99,None,0.5,True
14,04698622-e165-4091-bfe4-1ad84c260e62,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Puten-Geschnetzeltes 4,59 x 2 9,18 A",Puten-Geschnetzeltes,2.000,piece,9.18,None,0.9,False
15,55291075-9ffb-4162-8ccf-166c07fed72d,8d554238-2f93-4096-9d0c-e0a516bcda25,IMG_1928.JPG,"745 7] Geg, BAR EUR 1,20 EST","745 7] Geg, BAR EUR",1.000,piece,1.20,None,0.5,True
16,ab7d696c-4b00-4199-a13a-ff6ab59c07fa,8d554238-2f93-4096-9d0c-e0a516bcda25,IMG_1928.JPG,"Sn DS B= 7,0% 1,11 0,08 1,19 nm","Sn DS B= 1,11 0,08",1.000,piece,1.19,None,0.5,True
17,193062e7-7777-4c7b-9262-ed4041379b04,30bb7241-c4aa-4d61-ba68-9eeffa94c335,IMG_1929.JPG,"‚ Miracel Whip 1,49€x 3 4,47 AW",Miracel Whip,3.000,piece,4.47,None,0.9,False
18,ba126edb-6968-42b9-96cc-1f2c35e37476,30bb7241-c4aa-4d61-ba68-9eeffa94c335,IMG_1929.JPG,"| Frischfi,erm,BED 3,98 A","Frischfi,erm,BED",1.000,piece,3.98,None,0.5,True
19,d131a00e-3aef-44b9-87b0-4d9c1af7c5f0,30bb7241-c4aa-4d61-ba68-9eeffa94c335,IMG_1929.JPG,"/ Lang.Cremiss.Eis 1,89 AM",Lang.Cremiss.Eis,1.000,piece,1.89,None,0.5,True
20,7a4f68fa-72d1-446a-b290-807f3b1cc19c,30bb7241-c4aa-4d61-ba68-9eeffa94c335,IMG_1929.JPG,"Harry Sonntag 0,15 € x 5 0,75 AM",Harry Sonntag,5.000,piece,0.75,None,0.9,False
21,afc3e0a0-413f-45c3-9895-d152be5d0a74,30bb7241-c4aa-4d61-ba68-9eeffa94c335,IMG_1929.JPG,"/ THUER ,METT/HACKEP. 1,20 AM","THUER ,METT/HACKEP",1.000,piece,1.20,None,0.5,True
22,c6fdcaf2-284c-49fb-88f1-c1f715c64821,30bb7241-c4aa-4d61-ba68-9eeffa94c335,IMG_1929.JPG,"| THUER.METT/HACKEP, 1,21 AW",THUER.METT/HACKEP,1.000,piece,1.21,None,0.5,True
23,b5b14672-8439-41f0-aeef-9c6059ca3c69,30bb7241-c4aa-4d61-ba68-9eeffa94c335,IMG_1929.JPG,"_ GURKEN ‚ 0,49€x% 2 0,98 AM",GURKEN ‚,2.000,piece,0.98,None,0.9,False
24,adedcd12-0740-413c-8770-fd0b07183fbe,30bb7241-c4aa-4d61-ba68-9eeffa94c335,IMG_1929.JPG,"‚ Vand.Mai Gouda 2,58 AW",Vand.Mai Gouda,1.000,piece,2.58,None,0.5,True
25,dd81621a-b787-4bdd-bffe-e5c490505d2f,0c84d1cd-e2b1-4873-af7a-31d06e600720,IMG_1937.PNG,"Bulgur Rote Beete 2,49 B",Bulgur Rote Beete,1.000,piece,2.49,None,0.5,True
26,2d0ab919-23f3-4b5c-9972-6c76d9ffd534,b8398cde-f425-4a5c-985f-7f40f2c6276e,Netto_Kassenbon_20260702-191137.pdf,Favora Topa 3lg. 10x220BL,Favora Topa 3lg. 10x220BL,1.000,piece,3.85,None,0.9,False
27,f24d9a9a-8fa0-4922-a4e0-b17c395037fa,b8398cde-f425-4a5c-985f-7f40f2c6276e,Netto_Kassenbon_20260702-191137.pdf,Pri.Zugb.muellbtl.25x60L,Pri.Zugb.muellbtl.25,60.000,l,1.89,None,0.9,False
28,75364570-9157-417c-8ed2-4165a77d6298,b8398cde-f425-4a5c-985f-7f40f2c6276e,Netto_Kassenbon_20260702-191137.pdf,BesteErnte Himbeeren 500g,BesteErnte Himbeeren,500.000,g,4.99,None,0.9,False
29,4cb8bdaf-233b-4ddf-b22c-beedf7bcedc5,b8398cde-f425-4a5c-985f-7f40f2c6276e,Netto_Kassenbon_20260702-191137.pdf,Ostm.Paprika ger. gem.50g,Ostm.Paprika ger. gem,50.000,g,2.59,None,0.9,False
30,dcb6f9be-4339-43ff-81bd-2d586f0bc6c0,cc8c3543-623d-4ff6-ae83-a22028742571,Netto_Kassenbon_20260707-180115.pdf,Beste Ernte Kichererbsen 265g,Beste Ernte Kichererbsen,265.000,g,0.59,None,0.9,False
31,45e66d24-8b19-45e7-9019-73f10fb8d2ba,cc8c3543-623d-4ff6-ae83-a22028742571,Netto_Kassenbon_20260707-180115.pdf,Beste Ernte Kidneybohnen 255g,Beste Ernte Kidneybohnen,255.000,g,0.69,None,0.9,False
32,97246d4b-c38d-43e9-be02-7bb5ab8c85b6,cc8c3543-623d-4ff6-ae83-a22028742571,Netto_Kassenbon_20260707-180115.pdf,Irische Butter Kerrygold 250g,Irische Butter Kerrygold,250.000,g,1.49,None,0.9,False
33,ece54d8d-31dd-46b8-9ccf-a081e05abced,cc8c3543-623d-4ff6-ae83-a22028742571,Netto_Kassenbon_20260707-180115.pdf,Bio BB Feta 200g,Bio BB Feta,200.000,g,2.69,None,0.9,False
34,1be0e269-aa35-4dbf-8f5e-9045a652cc0f,cc8c3543-623d-4ff6-ae83-a22028742571,Netto_Kassenbon_20260707-180115.pdf,Bio Paprika Mix 400g,Bio Paprika Mi,400.000,g,1.99,None,0.9,False
35,6a4c07c6-d254-4ca4-8e3d-9f319ad1551b,cc8c3543-623d-4ff6-ae83-a22028742571,Netto_Kassenbon_20260707-180115.pdf,Minigurken 750g,Minigurken,750.000,g,1.99,None,0.9,False
36,0a2f3d61-f330-4467-a612-2a3bb0d67dc6,cc8c3543-623d-4ff6-ae83-a22028742571,Netto_Kassenbon_20260707-180115.pdf,Minipflaumen Tomaten 500g,Minipflaumen Tomaten,500.000,g,1.99,None,0.9,False
37,edf22484-658c-4782-b921-d16f8dfa320e,cc8c3543-623d-4ff6-ae83-a22028742571,Netto_Kassenbon_20260707-180115.pdf,Bananen Lose MT,Bananen Lose MT,1.266,kg,1.63,None,0.9,False
38,7e6ee9c0-9991-4ad7-bd58-9eb3c91dea3a,cc8c3543-623d-4ff6-ae83-a22028742571,Netto_Kassenbon_20260707-180115.pdf,Lauchzwiebeln,Lauchzwiebeln,1.000,piece,0.55,None,0.9,False
39,30b46fef-1ce4-48a9-a2d8-0cc8f38602f9,cc8c3543-623d-4ff6-ae83-a22028742571,Netto_Kassenbon_20260707-180115.pdf,Apfel Pink Lady Lose,Apfel Pink Lady Lose,0.182,kg,0.54,None,0.9,False
40,c90aacff-eb4a-4099-9997-d385d3fceb9c,34440959-7870-49fe-85cd-7a227d4cbb39,Netto_Kassenbon_20260709-172131.pdf,VL Eier FH 10ST,VL Eier FH,10.000,piece,2.99,None,0.9,False
41,1d24e3f8-23b8-44e2-8301-1e005e880436,34440959-7870-49fe-85cd-7a227d4cbb39,Netto_Kassenbon_20260709-172131.pdf,LiekenUrkornMehrkorn500g,LiekenUrkornMehrkorn,500.000,g,1.49,None,0.9,False
42,6235094a-2a6b-4e85-b71e-aabefd52b123,34440959-7870-49fe-85cd-7a227d4cbb39,Netto_Kassenbon_20260709-172131.pdf,Ostmann.Oregano gerebelt.25g,Ostmann.Oregano gerebelt,25.000,g,2.99,None,0.9,False
43,1be4f37d-4e2c-45c1-b97f-3acfe85da251,34440959-7870-49fe-85cd-7a227d4cbb39,Netto_Kassenbon_20260709-172131.pdf,Ostm.Rosmarin geschn.50g,Ostm.Rosmarin geschn,50.000,g,2.99,None,0.9,False
44,350f554f-ee1d-4830-a22f-a7a0d037ca20,34440959-7870-49fe-85cd-7a227d4cbb39,Netto_Kassenbon_20260709-172131.pdf,AIRWAVESCoolCassis50ST,AIRWAVESCoolCassis,50.000,piece,2.95,None,0.9,False
45,c6afbb70-9b4c-493d-ba6b-39e4ff926e0f,4e42fe7b-680a-4843-9139-e92784c3cc31,Netto_Kassenbon_20260713-170620.pdf,Beste Ernte Kidneybohnen 255g,Beste Ernte Kidneybohnen,255.000,g,0.69,None,0.9,False
46,f4da6489-95ec-415e-8272-e017f469b7d6,4e42fe7b-680a-4843-9139-e92784c3cc31,Netto_Kassenbon_20260713-170620.pdf,VL Eier FH 10ST,VL Eier FH,10.000,piece,2.99,None,0.9,False
47,15603730-0ae4-452d-a56c-abece0adcc8f,4e42fe7b-680a-4843-9139-e92784c3cc31,Netto_Kassenbon_20260713-170620.pdf,Beste Ernte Kichererbsen 265g,Beste Ernte Kichererbsen,265.000,g,0.59,None,0.9,False
48,34d777b0-3c3d-4289-bb97-7bda672883ab,4e42fe7b-680a-4843-9139-e92784c3cc31,Netto_Kassenbon_20260713-170620.pdf,Lieken Urkorn Fitnessbrot 500g,Lieken Urkorn Fitnessbrot,500.000,g,1.89,None,0.9,False
49,075c47b9-f6e9-4543-ab3c-620dbd9384a7,4e42fe7b-680a-4843-9139-e92784c3cc31,Netto_Kassenbon_20260713-170620.pdf,Bio BB Feta 200g,Bio BB Feta,200.000,g,2.42,None,0.9,False
50,4a390def-2faf-4a85-8b10-d2a5f4d43bb7,4e42fe7b-680a-4843-9139-e92784c3cc31,Netto_Kassenbon_20260713-170620.pdf,Paprika rot 500g,Paprika rot,500.000,g,1.79,None,0.9,False
51,6be1e416-52cc-4ec3-b9ff-e47d04752a72,4e42fe7b-680a-4843-9139-e92784c3cc31,Netto_Kassenbon_20260713-170620.pdf,Bio Naturland Speisem. 1kg,Bio Naturland Speisem,1.000,kg,1.97,None,0.9,False
52,49e3b20f-83e7-430a-877a-1436fea2917e,4e42fe7b-680a-4843-9139-e92784c3cc31,Netto_Kassenbon_20260713-170620.pdf,Bio NL Zucchini 500g,Bio NL Zucchini,500.000,g,1.61,None,0.9,False
53,50d00a4a-f7d8-4b55-9c1b-b1dfea827217,4e42fe7b-680a-4843-9139-e92784c3cc31,Netto_Kassenbon_20260713-170620.pdf,Bananen Lose MT,Bananen Lose MT,0.958,kg,1.24,None,0.9,False
54,6e5d92d7-d169-465c-b770-c7482bc47fae,4e42fe7b-680a-4843-9139-e92784c3cc31,Netto_Kassenbon_20260713-170620.pdf,Lauchzwiebeln,Lauchzwiebeln,1.000,piece,0.69,None,0.9,False
55,0f3d1d00-e6e8-4e7c-abf4-0d18eee78d3b,4e42fe7b-680a-4843-9139-e92784c3cc31,Netto_Kassenbon_20260713-170620.pdf,Broccoli 500g VKE,Broccoli VKE,500.000,g,1.11,None,0.9,False
56,57ee92b3-7727-471f-9e76-4ded987e520b,4e42fe7b-680a-4843-9139-e92784c3cc31,Netto_Kassenbon_20260713-170620.pdf,Bio BB SB R-Hackfl.400g,Bio BB SB R-Hackfl,400.000,g,5.84,None,0.9,False
57,e6eef507-7a5c-4b7e-870e-32aebd62f7bf,93fe7ca9-440a-448a-ab79-0d6024d6b114,Netto_Kassenbon_20260714-133412.pdf,Carat Jodsalz mit Fluorid 500g,Carat Jodsalz mit Fluorid,500.000,g,0.29,None,0.9,False
58,4824d78b-1d66-4f7d-85a0-6065c5be60e5,93fe7ca9-440a-448a-ab79-0d6024d6b114,Netto_Kassenbon_20260714-133412.pdf,Clarkys Walnusskerne 200g,Clarkys Walnusskerne,200.000,g,2.99,None,0.9,False
59,ddd5d4a3-d269-409e-af33-8a672e02f0af,93fe7ca9-440a-448a-ab79-0d6024d6b114,Netto_Kassenbon_20260714-133412.pdf,Clarkys Cashewkerne 200g,Clarkys Cashewkerne,200.000,g,2.89,None,0.9,False
60,993b77a1-c4b7-4390-8480-03ad8d1263ca,93fe7ca9-440a-448a-ab79-0d6024d6b114,Netto_Kassenbon_20260714-133412.pdf,VL Eier FH 10ST,VL Eier FH,10.000,piece,2.99,None,0.9,False
61,97ceedee-30f5-48d3-8e56-2a865851bd6e,93fe7ca9-440a-448a-ab79-0d6024d6b114,Netto_Kassenbon_20260714-133412.pdf,Tomaten-Mix 500g VKE,Tomaten-Mix VKE,500.000,g,2.79,None,0.9,False
62,3bcc431a-aa15-4d16-8163-ea6406b7f6a1,33275a24-9b52-4be6-b4aa-24302b613a7e,Netto_Kassenbon_20260716-095742.pdf,GT Toast sort. 250g,GT Toast sort,250.000,g,1.29,None,0.9,False
63,802cae95-5985-4dc0-bd1c-37a48b60448e,33275a24-9b52-4be6-b4aa-24302b613a7e,Netto_Kassenbon_20260716-095742.pdf,GW Hummus Pikant 200 G,GW Hummus Pikant,200.000,g,0.99,None,0.9,False
64,70aadb00-98d8-4023-9cda-5349a5e658f2,33275a24-9b52-4be6-b4aa-24302b613a7e,Netto_Kassenbon_20260716-095742.pdf,Bananen Lose MT,Bananen Lose MT,1.404,kg,1.81,None,0.9,False
65,cfc0e7de-f3e5-46a0-b777-d2dc3009913d,1cc77841-5cc2-42fb-a4b4-dce2cbfa7dfe,WhatsApp Image 2026-07-05 at 11.02.48.jpeg,"Z EUR 13,36",Z EUR,1.000,piece,13.36,None,0.5,True
66,55415a6a-eb59-4217-85f8-bef05ea805f0,c1b9409e-6f60-423d-9495-5a5339261809,WhatsApp Image 2026-07-16 at 13.05.02.jpeg,"Apfel rot süß 0,53 A",Apfel rot süß,0.232,kg,0.53,None,0.5,True
67,c2cc29c7-bbc4-421f-b89e-33ff74cff0a3,c1b9409e-6f60-423d-9495-5a5339261809,WhatsApp Image 2026-07-16 at 13.05.02.jpeg,"Avocado vorger. 1,19x 2 2,38 A",Avocado vorger,2.000,piece,2.38,None,0.9,False
68,dc695d6e-811e-419e-8bc7-23b27a6f56a2,c1b9409e-6f60-423d-9495-5a5339261809,WhatsApp Image 2026-07-16 at 13.05.02.jpeg,"Bio Limetten 1,89 A",Bio Limetten,1.000,piece,1.89,None,0.5,True
69,f1f96eec-94fb-4209-8126-27b69dc8c7dd,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Banane lose 1,14 A",Banane lose,0.886,kg,1.14,None,0.5,True
70,42ed564f-cad7-4143-bcb5-715b3e8d0a39,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Lachsfilet mit Haut 21,74 A",Lachsfilet mit Haut,1.145,kg,21.74,None,0.5,True
71,0ca84b13-b6fd-4517-86c2-6307aa16612b,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Kohl Spitz 1,59 A",Kohl Spitz,1.142,kg,1.59,None,0.5,True
72,1680956f-629f-43b9-a47f-9095fcae06fc,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Apfel grün 0,43 A",Apfel grün,1.000,piece,0.43,None,0.5,True
73,e37630cb-bac7-440a-b10b-d3695cf1db2c,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Staudensellerie 1,11 A",Staudensellerie,1.000,piece,1.11,None,0.5,True
74,3c5503f6-1292-4759-bed6-8083db47d981,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Avocado varger. 1,19 x 2 2,38 A",Avocado varger,2.000,piece,2.38,None,0.9,False
75,f671059f-c702-4606-9112-16174aea89a9,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Bio Birnen 500g 2,19 A",Bio Birnen,500.000,g,2.19,None,0.9,False
76,94f16c40-75fb-408a-a5cd-f41914c0bd34,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Bio Broccoli 1,99 x 2 3,98 A",Bio Broccoli,2.000,piece,3.98,None,0.9,False
77,efb2b680-b9d3-4f47-a1ef-b8b5ed1e1b7f,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Spinat 2,49 A",Spinat,1.000,piece,2.49,None,0.5,True
78,e8d1eed0-eae5-4b22-9203-7b6914d248c3,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Bioland Speisek 2,29 A",Bioland Speisek,1.000,piece,2.29,None,0.5,True
79,6395378c-27bc-49bc-a7f9-d9422cec13c7,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Knoblauch 0,99% 2 1,98 A",Knoblauch 2,1.000,piece,1.98,None,0.5,True
80,b5d998f5-0eb4-4431-8eec-32f3cd91beb1,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Blumenkohl 1,79 A",Blumenkohl,1.000,piece,1.79,None,0.5,True
81,89cb71f2-b41b-49f2-a044-5eb48c84f95b,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Bio Gurken 1,59 A",Bio Gurken,1.000,piece,1.59,None,0.5,True
82,2146888b-7a6e-49a2-b38a-08ec94afe4f5,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Zulebeln rot 0,99 A",Zulebeln rot,1.000,piece,0.99,None,0.5,True
83,c09ad7e6-8924-4415-9464-321056486512,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Raclette-Käse 3,99 A",Raclette-Käse,1.000,piece,3.99,None,0.5,True
84,a379e4df-be3e-40e0-9e68-ceb359760928,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Bioland Tofu natur 2,29Xx% 2 4,53 A","Bioland Tofu natur 2,29Xx% 2",2.000,piece,4.53,None,0.9,False
85,1bfb0b02-5d50-476e-8713-9f4bbf441d94,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Schott.Räucherlachs 2,99 A",Schott.Räucherlachs,1.000,piece,2.99,None,0.5,True
86,21248490-2a10-4b46-bbe2-dd617146419e,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Bio Griıech. Feta 2,89 A",Bio Griıech. Feta,1.000,piece,2.89,None,0.5,True
87,35940552-6f8b-41d4-9387-fa7608ebf9d8,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Griech, Joghurt 2% 2,29 A","Griech, Joghurt",1.000,piece,2.29,None,0.5,True
88,71b65965-3135-4192-9583-2f4de5704385,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Kräuterbutter 1,19 A",Kräuterbutter,1.000,piece,1.19,None,0.5,True
89,a64ca184-6b6d-491d-9c9a-e9f8b7649d4c,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Hummus Ras el-Hanout 0,99 A",Hummus Ras el-Hanout,1.000,piece,0.99,None,0.5,True
90,2385a8a8-c69d-463a-82d4-62e19ee3109f,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Spreewälder Gurken 2,59 A",Spreewälder Gurken,1.000,piece,2.59,None,0.5,True
91,6113e996-4846-4cb3-a368-f65c89390cff,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Oro d,P stück.Tomate 1,99 A","Oro d,P stück.Tomate",1.000,piece,1.99,None,0.5,True
92,00d083bd-981e-4c3a-9a92-b54852784508,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Don Papa Baroko 40% 29,99 B",Don Papa Baroko,1.000,piece,29.99,None,0.5,True
93,53125fd8-1771-4d9f-95ba-86525340f4af,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Harry KörnerSandwich 2,49 A",Harry KörnerSandwich,1.000,piece,2.49,None,0.5,True
94,c20091cf-3722-4ff0-9893-4fed7b71f094,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Cashewkerne 200g 2,99 A",Cashewkerne,200.000,g,2.99,None,0.9,False
95,10450f3e-8f2a-46b6-b7ab-fa68b4794a1b,f0047fbc-d166-45a8-bd62-5e38eba44e23,WhatsApp Image 2026-07-16 at 13.05.48.jpeg,"Auberginen 0,97 A",Auberginen,0.286,kg,0.97,None,0.5,True
96,dcf8b74a-4e0c-4aee-ae89-554db5ef42b2,f0047fbc-d166-45a8-bd62-5e38eba44e23,WhatsApp Image 2026-07-16 at 13.05.48.jpeg,"Kartoffeln S0ß 0,81 B",Kartoffeln S0ß,0.450,kg,0.81,None,0.5,True
97,e2356a83-5549-4eed-9fd9-e740db868d30,f0047fbc-d166-45a8-bd62-5e38eba44e23,WhatsApp Image 2026-07-16 at 13.05.48.jpeg,"Bananen Fairtra 1,72 A",Bananen Fairtra,1.000,piece,1.72,None,0.5,True
98,db8b2546-9a37-4214-ac3d-6c31e6933ed3,f0047fbc-d166-45a8-bd62-5e38eba44e23,WhatsApp Image 2026-07-16 at 13.05.48.jpeg,"Avocado vorger. 0,99 A",Avocado vorger,1.000,piece,0.99,None,0.5,True
99,240f5c7a-8e46-4357-8b82-befca5d2f7e0,f0047fbc-d166-45a8-bd62-5e38eba44e23,WhatsApp Image 2026-07-16 at 13.05.48.jpeg,"Zitronen Blo 0,79 A",Zitronen Blo,1.000,piece,0.79,None,0.5,True
100,e769ab9a-4776-4c17-815e-9b3a86987b9e,f0047fbc-d166-45a8-bd62-5e38eba44e23,WhatsApp Image 2026-07-16 at 13.05.48.jpeg,"Speisekartoffeln 1,79 A",Speisekartoffeln,1.000,piece,1.79,None,0.5,True
101,5607da5d-93b1-4aff-9d45-a089d770ee13,f0047fbc-d166-45a8-bd62-5e38eba44e23,WhatsApp Image 2026-07-16 at 13.05.48.jpeg,"Broccoli 1,19 x 2 2,38 A",Broccoli,2.000,piece,2.38,None,0.9,False
102,8d837125-7144-47ea-b3b7-71361a770738,f0047fbc-d166-45a8-bd62-5e38eba44e23,WhatsApp Image 2026-07-16 at 13.05.48.jpeg,"Bio Zucchini 1,89 A",Bio Zucchini,1.000,piece,1.89,None,0.5,True
103,c84262fb-81dd-4ff0-91c4-252201f425a6,f0047fbc-d166-45a8-bd62-5e38eba44e23,WhatsApp Image 2026-07-16 at 13.05.48.jpeg,"Blumenkohl 1,79 A",Blumenkohl,1.000,piece,1.79,None,0.5,True
104,0484f1de-288c-4b1e-8699-02a38c59656e,f0047fbc-d166-45a8-bd62-5e38eba44e23,WhatsApp Image 2026-07-16 at 13.05.48.jpeg,"Bio Paprika rot 1,59 A",Bio Paprika rot,1.000,piece,1.59,None,0.5,True
105,928b4ddb-208e-4f13-ac5e-749e98117808,f0047fbc-d166-45a8-bd62-5e38eba44e23,WhatsApp Image 2026-07-16 at 13.05.48.jpeg,"Bioland Tofu geräu. 2,29 A",Bioland Tofu geräu,1.000,piece,2.29,None,0.5,True

### Combined view

Items joined back with their receipt's metadata (file name, store, purchase date) — one flat table, easiest to eyeball or export.

In [6]:
df_combined = df_items.merge(
    df_receipts[["receipt_id", "store", "purchase_date", "scan_quality"]],
    on="receipt_id",
    how="left",
)
df_combined

,item_id,receipt_id,file_name,raw_name,normalized_name,quantity,unit,price,matched_product_id,confidence,uncertain,store,purchase_date,scan_quality
0,1827153b-b012-453b-926f-c3df158cae91,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Banane Fair Bio 2,35 A",Banane Fair Bio,1.182,kg,2.35,None,0.5,True,Lidl,2026-06-30,good
1,592f30db-ea4d-4418-a314-b03d96f7a074,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Zwiebeln weiß 1,28 A",Zwiebeln weiß,0.356,kg,1.28,None,0.5,True,Lidl,2026-06-30,good
2,97af5108-17a5-480b-af76-e0f0b2e841f3,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Bioland Zucchini 1,49 A",Bioland Zucchini,1.000,piece,1.49,None,0.5,True,Lidl,2026-06-30,good
3,c3138c2f-675b-4c0d-9b6b-37c3472fcd15,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Petersilie 1,39 A",Petersilie,1.000,piece,1.39,None,0.5,True,Lidl,2026-06-30,good
4,517fc874-ad36-4723-9408-0ba10f7861d5,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Bio Limetten 1,99 A",Bio Limetten,1.000,piece,1.99,None,0.5,True,Lidl,2026-06-30,good
5,c9574418-4e27-40cd-b21c-4fab8a121b8b,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Weidemilch 3,8% 1,19 A",Weidemilch,1.000,piece,1.19,None,0.5,True,Lidl,2026-06-30,good
6,5cc0d5e7-9b8b-483e-a5c4-0159e175d6a9,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Exquisa fitlineNatur 1,59 A",Exquisa fitlineNatur,1.000,piece,1.59,None,0.5,True,Lidl,2026-06-30,good
7,6bf23279-4d79-4a28-a525-71f9f4ee9f2c,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Bio-Eier OKT 10er 3,99 A",Bio-Eier OKT 10er,1.000,piece,3.99,None,0.5,True,Lidl,2026-06-30,good
8,1edac537-14b2-4b64-a470-76646701ce9e,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Bio Müsli Schoko Kn. 2,65 A",Bio Müsli Schoko Kn,1.000,piece,2.65,None,0.5,True,Lidl,2026-06-30,good
9,cd8d9096-6e3c-420a-b96e-c2e89daa45c6,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Lava Bar Cookie 1,69 A",Lava Bar Cookie,1.000,piece,1.69,None,0.5,True,Lidl,2026-06-30,good
10,9ea14ff0-24a4-4c65-ad0c-37256157f77e,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Dinkelschnitte 1,29 A",Dinkelschnitte,1.000,piece,1.29,None,0.5,True,Lidl,2026-06-30,good
11,e93b8d45-287f-4410-a47f-e67a3d2d9a7b,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Walnusskerne 2,99 A",Walnusskerne,1.000,piece,2.99,None,0.5,True,Lidl,2026-06-30,good
12,80f8e9ca-c1bd-44f9-b400-db164f8495af,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Bio Cashewkerne 2,45 A",Bio Cashewkerne,1.000,piece,2.45,None,0.5,True,Lidl,2026-06-30,good
13,cf4cd0f6-9400-48c4-acd2-a4e4484b7648,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Rinderhackfleisch 5% 5,99 A",Rinderhackfleisch,1.000,piece,5.99,None,0.5,True,Lidl,2026-06-30,good
14,04698622-e165-4091-bfe4-1ad84c260e62,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Puten-Geschnetzeltes 4,59 x 2 9,18 A",Puten-Geschnetzeltes,2.000,piece,9.18,None,0.9,False,Lidl,2026-06-30,good
15,55291075-9ffb-4162-8ccf-166c07fed72d,8d554238-2f93-4096-9d0c-e0a516bcda25,IMG_1928.JPG,"745 7] Geg, BAR EUR 1,20 EST","745 7] Geg, BAR EUR",1.000,piece,1.20,None,0.5,True,Netto,2026-06-17,good
16,ab7d696c-4b00-4199-a13a-ff6ab59c07fa,8d554238-2f93-4096-9d0c-e0a516bcda25,IMG_1928.JPG,"Sn DS B= 7,0% 1,11 0,08 1,19 nm","Sn DS B= 1,11 0,08",1.000,piece,1.19,None,0.5,True,Netto,2026-06-17,good
17,193062e7-7777-4c7b-9262-ed4041379b04,30bb7241-c4aa-4d61-ba68-9eeffa94c335,IMG_1929.JPG,"‚ Miracel Whip 1,49€x 3 4,47 AW",Miracel Whip,3.000,piece,4.47,None,0.9,False,Edeka,NaN,good
18,ba126edb-6968-42b9-96cc-1f2c35e37476,30bb7241-c4aa-4d61-ba68-9eeffa94c335,IMG_1929.JPG,"| Frischfi,erm,BED 3,98 A","Frischfi,erm,BED",1.000,piece,3.98,None,0.5,True,Edeka,NaN,good
19,d131a00e-3aef-44b9-87b0-4d9c1af7c5f0,30bb7241-c4aa-4d61-ba68-9eeffa94c335,IMG_1929.JPG,"/ Lang.Cremiss.Eis 1,89 AM",Lang.Cremiss.Eis,1.000,piece,1.89,None,0.5,True,Edeka,NaN,good
20,7a4f68fa-72d1-446a-b290-807f3b1cc19c,30bb7241-c4aa-4d61-ba68-9eeffa94c335,IMG_1929.JPG,"Harry Sonntag 0,15 € x 5 0,75 AM",Harry Sonntag,5.000,piece,0.75,None,0.9,False,Edeka,NaN,good
21,afc3e0a0-413f-45c3-9895-d152be5d0a74,30bb7241-c4aa-4d61-ba68-9eeffa94c335,IMG_1929.JPG,"/ THUER ,METT/HACKEP. 1,20 AM","THUER ,METT/HACKEP",1.000,piece,1.20,None,0.5,True,Edeka,NaN,good
22,c6fdcaf2-284c-49fb-88f1-c1f715c64821,30bb7241-c4aa-4d61-ba68-9eeffa94c335,IMG_1929.JPG,"| THUER.METT/HACKEP, 1,21 AW",THUER.METT/HACKEP,1.000,piece,1.21,None,0.5,True,Edeka,NaN,good
23,b5b14672-8439-41f0-aeef-9c6059ca3c69,30bb7241-c4aa-4d61-ba68-9eeffa94c335,IMG_1929.JPG,"_ GURKEN ‚ 0,49€x% 2 0,98 AM",GURKEN ‚,2.000,piece,0.98,None,0.9,False,Edeka,NaN,good
24,adedcd12-0740-413c-8770-fd0b07183fbe,30bb7241-c4aa-4d61-ba68-9eeffa94c335,IMG_1929.JPG,"‚ Vand.Mai Gouda 2,58 AW",Vand.Mai Gouda,1.000,piece,2.58,None,0.5,True,Edeka,NaN,good
25,dd81621a-b787-4bdd-bffe-e5c490505d2f,0c84d1cd-e2b1-4873-af7a-31d06e600720,IMG_1937.PNG,"Bulgur Rote Beete 2,49 B",Bulgur Rote Beete,1.000,piece,2.49,None,0.5,True,Kaufland,2026-06-15,good
26,2d0ab919-23f3-4b5c-9972-6c76d9ffd534,b8398cde-f425-4a5c-985f-7f40f2c6276e,Netto_Kassenbon_20260702-191137.pdf,Favora Topa 3lg. 10x220BL,Favora Topa 3lg. 10x220BL,1.000,piece,3.85,None,0.9,False,Netto,2026-07-02,good
27,f24d9a9a-8fa0-4922-a4e0-b17c395037fa,b8398cde-f425-4a5c-985f-7f40f2c6276e,Netto_Kassenbon_20260702-191137.pdf,Pri.Zugb.muellbtl.25x60L,Pri.Zugb.muellbtl.25,60.000,l,1.89,None,0.9,False,Netto,2026-07-02,good
28,75364570-9157-417c-8ed2-4165a77d6298,b8398cde-f425-4a5c-985f-7f40f2c6276e,Netto_Kassenbon_20260702-191137.pdf,BesteErnte Himbeeren 500g,BesteErnte Himbeeren,500.000,g,4.99,None,0.9,False,Netto,2026-07-02,good
29,4cb8bdaf-233b-4ddf-b22c-beedf7bcedc5,b8398cde-f425-4a5c-985f-7f40f2c6276e,Netto_Kassenbon_20260702-191137.pdf,Ostm.Paprika ger. gem.50g,Ostm.Paprika ger. gem,50.000,g,2.59,None,0.9,False,Netto,2026-07-02,good
30,dcb6f9be-4339-43ff-81bd-2d586f0bc6c0,cc8c3543-623d-4ff6-ae83-a22028742571,Netto_Kassenbon_20260707-180115.pdf,Beste Ernte Kichererbsen 265g,Beste Ernte Kichererbsen,265.000,g,0.59,None,0.9,False,Netto,2026-07-07,good
31,45e66d24-8b19-45e7-9019-73f10fb8d2ba,cc8c3543-623d-4ff6-ae83-a22028742571,Netto_Kassenbon_20260707-180115.pdf,Beste Ernte Kidneybohnen 255g,Beste Ernte Kidneybohnen,255.000,g,0.69,None,0.9,False,Netto,2026-07-07,good
32,97246d4b-c38d-43e9-be02-7bb5ab8c85b6,cc8c3543-623d-4ff6-ae83-a22028742571,Netto_Kassenbon_20260707-180115.pdf,Irische Butter Kerrygold 250g,Irische Butter Kerrygold,250.000,g,1.49,None,0.9,False,Netto,2026-07-07,good
33,ece54d8d-31dd-46b8-9ccf-a081e05abced,cc8c3543-623d-4ff6-ae83-a22028742571,Netto_Kassenbon_20260707-180115.pdf,Bio BB Feta 200g,Bio BB Feta,200.000,g,2.69,None,0.9,False,Netto,2026-07-07,good
34,1be0e269-aa35-4dbf-8f5e-9045a652cc0f,cc8c3543-623d-4ff6-ae83-a22028742571,Netto_Kassenbon_20260707-180115.pdf,Bio Paprika Mix 400g,Bio Paprika Mi,400.000,g,1.99,None,0.9,False,Netto,2026-07-07,good
35,6a4c07c6-d254-4ca4-8e3d-9f319ad1551b,cc8c3543-623d-4ff6-ae83-a22028742571,Netto_Kassenbon_20260707-180115.pdf,Minigurken 750g,Minigurken,750.000,g,1.99,None,0.9,False,Netto,2026-07-07,good
36,0a2f3d61-f330-4467-a612-2a3bb0d67dc6,cc8c3543-623d-4ff6-ae83-a22028742571,Netto_Kassenbon_20260707-180115.pdf,Minipflaumen Tomaten 500g,Minipflaumen Tomaten,500.000,g,1.99,None,0.9,False,Netto,2026-07-07,good
37,edf22484-658c-4782-b921-d16f8dfa320e,cc8c3543-623d-4ff6-ae83-a22028742571,Netto_Kassenbon_20260707-180115.pdf,Bananen Lose MT,Bananen Lose MT,1.266,kg,1.63,None,0.9,False,Netto,2026-07-07,good
38,7e6ee9c0-9991-4ad7-bd58-9eb3c91dea3a,cc8c3543-623d-4ff6-ae83-a22028742571,Netto_Kassenbon_20260707-180115.pdf,Lauchzwiebeln,Lauchzwiebeln,1.000,piece,0.55,None,0.9,False,Netto,2026-07-07,good
39,30b46fef-1ce4-48a9-a2d8-0cc8f38602f9,cc8c3543-623d-4ff6-ae83-a22028742571,Netto_Kassenbon_20260707-180115.pdf,Apfel Pink Lady Lose,Apfel Pink Lady Lose,0.182,kg,0.54,None,0.9,False,Netto,2026-07-07,good
40,c90aacff-eb4a-4099-9997-d385d3fceb9c,34440959-7870-49fe-85cd-7a227d4cbb39,Netto_Kassenbon_20260709-172131.pdf,VL Eier FH 10ST,VL Eier FH,10.000,piece,2.99,None,0.9,False,Netto,2026-07-09,good
41,1d24e3f8-23b8-44e2-8301-1e005e880436,34440959-7870-49fe-85cd-7a227d4cbb39,Netto_Kassenbon_20260709-172131.pdf,LiekenUrkornMehrkorn500g,LiekenUrkornMehrkorn,500.000,g,1.49,None,0.9,False,Netto,2026-07-09,good
42,6235094a-2a6b-4e85-b71e-aabefd52b123,34440959-7870-49fe-85cd-7a227d4cbb39,Netto_Kassenbon_20260709-172131.pdf,Ostmann.Oregano gerebelt.25g,Ostmann.Oregano gerebelt,25.000,g,2.99,None,0.9,False,Netto,2026-07-09,good
43,1be4f37d-4e2c-45c1-b97f-3acfe85da251,34440959-7870-49fe-85cd-7a227d4cbb39,Netto_Kassenbon_20260709-172131.pdf,Ostm.Rosmarin geschn.50g,Ostm.Rosmarin geschn,50.000,g,2.99,None,0.9,False,Netto,2026-07-09,good
44,350f554f-ee1d-4830-a22f-a7a0d037ca20,34440959-7870-49fe-85cd-7a227d4cbb39,Netto_Kassenbon_20260709-172131.pdf,AIRWAVESCoolCassis50ST,AIRWAVESCoolCassis,50.000,piece,2.95,None,0.9,False,Netto,2026-07-09,good
45,c6afbb70-9b4c-493d-ba6b-39e4ff926e0f,4e42fe7b-680a-4843-9139-e92784c3cc31,Netto_Kassenbon_20260713-170620.pdf,Beste Ernte Kidneybohnen 255g,Beste Ernte Kidneybohnen,255.000,g,0.69,None,0.9,False,Netto,2026-07-13,good
46,f4da6489-95ec-415e-8272-e017f469b7d6,4e42fe7b-680a-4843-9139-e92784c3cc31,Netto_Kassenbon_20260713-170620.pdf,VL Eier FH 10ST,VL Eier FH,10.000,piece,2.99,None,0.9,False,Netto,2026-07-13,good
47,15603730-0ae4-452d-a56c-abece0adcc8f,4e42fe7b-680a-4843-9139-e92784c3cc31,Netto_Kassenbon_20260713-170620.pdf,Beste Ernte Kichererbsen 265g,Beste Ernte Kichererbsen,265.000,g,0.59,None,0.9,False,Netto,2026-07-13,good
48,34d777b0-3c3d-4289-bb97-7bda672883ab,4e42fe7b-680a-4843-9139-e92784c3cc31,Netto_Kassenbon_20260713-170620.pdf,Lieken Urkorn Fitnessbrot 500g,Lieken Urkorn Fitnessbrot,500.000,g,1.89,None,0.9,False,Netto,2026-07-13,good
49,075c47b9-f6e9-4543-ab3c-620dbd9384a7,4e42fe7b-680a-4843-9139-e92784c3cc31,Netto_Kassenbon_20260713-170620.pdf,Bio BB Feta 200g,Bio BB Feta,200.000,g,2.42,None,0.9,False,Netto,2026-07-13,good
50,4a390def-2faf-4a85-8b10-d2a5f4d43bb7,4e42fe7b-680a-4843-9139-e92784c3cc31,Netto_Kassenbon_20260713-170620.pdf,Paprika rot 500g,Paprika rot,500.000,g,1.79,None,0.9,False,Netto,2026-07-13,good
51,6be1e416-52cc-4ec3-b9ff-e47d04752a72,4e42fe7b-680a-4843-9139-e92784c3cc31,Netto_Kassenbon_20260713-170620.pdf,Bio Naturland Speisem. 1kg,Bio Naturland Speisem,1.000,kg,1.97,None,0.9,False,Netto,2026-07-13,good
52,49e3b20f-83e7-430a-877a-1436fea2917e,4e42fe7b-680a-4843-9139-e92784c3cc31,Netto_Kassenbon_20260713-170620.pdf,Bio NL Zucchini 500g,Bio NL Zucchini,500.000,g,1.61,None,0.9,False,Netto,2026-07-13,good
53,50d00a4a-f7d8-4b55-9c1b-b1dfea827217,4e42fe7b-680a-4843-9139-e92784c3cc31,Netto_Kassenbon_20260713-170620.pdf,Bananen Lose MT,Bananen Lose MT,0.958,kg,1.24,None,0.9,False,Netto,2026-07-13,good
54,6e5d92d7-d169-465c-b770-c7482bc47fae,4e42fe7b-680a-4843-9139-e92784c3cc31,Netto_Kassenbon_20260713-170620.pdf,Lauchzwiebeln,Lauchzwiebeln,1.000,piece,0.69,None,0.9,False,Netto,2026-07-13,good
55,0f3d1d00-e6e8-4e7c-abf4-0d18eee78d3b,4e42fe7b-680a-4843-9139-e92784c3cc31,Netto_Kassenbon_20260713-170620.pdf,Broccoli 500g VKE,Broccoli VKE,500.000,g,1.11,None,0.9,False,Netto,2026-07-13,good
56,57ee92b3-7727-471f-9e76-4ded987e520b,4e42fe7b-680a-4843-9139-e92784c3cc31,Netto_Kassenbon_20260713-170620.pdf,Bio BB SB R-Hackfl.400g,Bio BB SB R-Hackfl,400.000,g,5.84,None,0.9,False,Netto,2026-07-13,good
57,e6eef507-7a5c-4b7e-870e-32aebd62f7bf,93fe7ca9-440a-448a-ab79-0d6024d6b114,Netto_Kassenbon_20260714-133412.pdf,Carat Jodsalz mit Fluorid 500g,Carat Jodsalz mit Fluorid,500.000,g,0.29,None,0.9,False,Netto,2026-07-14,good
58,4824d78b-1d66-4f7d-85a0-6065c5be60e5,93fe7ca9-440a-448a-ab79-0d6024d6b114,Netto_Kassenbon_20260714-133412.pdf,Clarkys Walnusskerne 200g,Clarkys Walnusskerne,200.000,g,2.99,None,0.9,False,Netto,2026-07-14,good
59,ddd5d4a3-d269-409e-af33-8a672e02f0af,93fe7ca9-440a-448a-ab79-0d6024d6b114,Netto_Kassenbon_20260714-133412.pdf,Clarkys Cashewkerne 200g,Clarkys Cashewkerne,200.000,g,2.89,None,0.9,False,Netto,2026-07-14,good
60,993b77a1-c4b7-4390-8480-03ad8d1263ca,93fe7ca9-440a-448a-ab79-0d6024d6b114,Netto_Kassenbon_20260714-133412.pdf,VL Eier FH 10ST,VL Eier FH,10.000,piece,2.99,None,0.9,False,Netto,2026-07-14,good
61,97ceedee-30f5-48d3-8e56-2a865851bd6e,93fe7ca9-440a-448a-ab79-0d6024d6b114,Netto_Kassenbon_20260714-133412.pdf,Tomaten-Mix 500g VKE,Tomaten-Mix VKE,500.000,g,2.79,None,0.9,False,Netto,2026-07-14,good
62,3bcc431a-aa15-4d16-8163-ea6406b7f6a1,33275a24-9b52-4be6-b4aa-24302b613a7e,Netto_Kassenbon_20260716-095742.pdf,GT Toast sort. 250g,GT Toast sort,250.000,g,1.29,None,0.9,False,Netto,2026-07-16,good
63,802cae95-5985-4dc0-bd1c-37a48b60448e,33275a24-9b52-4be6-b4aa-24302b613a7e,Netto_Kassenbon_20260716-095742.pdf,GW Hummus Pikant 200 G,GW Hummus Pikant,200.000,g,0.99,None,0.9,False,Netto,2026-07-16,good
64,70aadb00-98d8-4023-9cda-5349a5e658f2,33275a24-9b52-4be6-b4aa-24302b613a7e,Netto_Kassenbon_20260716-095742.pdf,Bananen Lose MT,Bananen Lose MT,1.404,kg,1.81,None,0.9,False,Netto,2026-07-16,good
65,cfc0e7de-f3e5-46a0-b777-d2dc3009913d,1cc77841-5cc2-42fb-a4b4-dce2cbfa7dfe,WhatsApp Image 2026-07-05 at 11.02.48.jpeg,"Z EUR 13,36",Z EUR,1.000,piece,13.36,None,0.5,True,unknown,NaN,good
66,55415a6a-eb59-4217-85f8-bef05ea805f0,c1b9409e-6f60-423d-9495-5a5339261809,WhatsApp Image 2026-07-16 at 13.05.02.jpeg,"Apfel rot süß 0,53 A",Apfel rot süß,0.232,kg,0.53,None,0.5,True,Lidl,2026-07-15,good
67,c2cc29c7-bbc4-421f-b89e-33ff74cff0a3,c1b9409e-6f60-423d-9495-5a5339261809,WhatsApp Image 2026-07-16 at 13.05.02.jpeg,"Avocado vorger. 1,19x 2 2,38 A",Avocado vorger,2.000,piece,2.38,None,0.9,False,Lidl,2026-07-15,good
68,dc695d6e-811e-419e-8bc7-23b27a6f56a2,c1b9409e-6f60-423d-9495-5a5339261809,WhatsApp Image 2026-07-16 at 13.05.02.jpeg,"Bio Limetten 1,89 A",Bio Limetten,1.000,piece,1.89,None,0.5,True,Lidl,2026-07-15,good
69,f1f96eec-94fb-4209-8126-27b69dc8c7dd,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Banane lose 1,14 A",Banane lose,0.886,kg,1.14,None,0.5,True,Lidl,2025-12-30,good
70,42ed564f-cad7-4143-bcb5-715b3e8d0a39,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Lachsfilet mit Haut 21,74 A",Lachsfilet mit Haut,1.145,kg,21.74,None,0.5,True,Lidl,2025-12-30,good
71,0ca84b13-b6fd-4517-86c2-6307aa16612b,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Kohl Spitz 1,59 A",Kohl Spitz,1.142,kg,1.59,None,0.5,True,Lidl,2025-12-30,good
72,1680956f-629f-43b9-a47f-9095fcae06fc,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Apfel grün 0,43 A",Apfel grün,1.000,piece,0.43,None,0.5,True,Lidl,2025-12-30,good
73,e37630cb-bac7-440a-b10b-d3695cf1db2c,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Staudensellerie 1,11 A",Staudensellerie,1.000,piece,1.11,None,0.5,True,Lidl,2025-12-30,good
74,3c5503f6-1292-4759-bed6-8083db47d981,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Avocado varger. 1,19 x 2 2,38 A",Avocado varger,2.000,piece,2.38,None,0.9,False,Lidl,2025-12-30,good
75,f671059f-c702-4606-9112-16174aea89a9,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Bio Birnen 500g 2,19 A",Bio Birnen,500.000,g,2.19,None,0.9,False,Lidl,2025-12-30,good
76,94f16c40-75fb-408a-a5cd-f41914c0bd34,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Bio Broccoli 1,99 x 2 3,98 A",Bio Broccoli,2.000,piece,3.98,None,0.9,False,Lidl,2025-12-30,good
77,efb2b680-b9d3-4f47-a1ef-b8b5ed1e1b7f,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Spinat 2,49 A",Spinat,1.000,piece,2.49,None,0.5,True,Lidl,2025-12-30,good
78,e8d1eed0-eae5-4b22-9203-7b6914d248c3,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Bioland Speisek 2,29 A",Bioland Speisek,1.000,piece,2.29,None,0.5,True,Lidl,2025-12-30,good
79,6395378c-27bc-49bc-a7f9-d9422cec13c7,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Knoblauch 0,99% 2 1,98 A",Knoblauch 2,1.000,piece,1.98,None,0.5,True,Lidl,2025-12-30,good
80,b5d998f5-0eb4-4431-8eec-32f3cd91beb1,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Blumenkohl 1,79 A",Blumenkohl,1.000,piece,1.79,None,0.5,True,Lidl,2025-12-30,good
81,89cb71f2-b41b-49f2-a044-5eb48c84f95b,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Bio Gurken 1,59 A",Bio Gurken,1.000,piece,1.59,None,0.5,True,Lidl,2025-12-30,good
82,2146888b-7a6e-49a2-b38a-08ec94afe4f5,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Zulebeln rot 0,99 A",Zulebeln rot,1.000,piece,0.99,None,0.5,True,Lidl,2025-12-30,good
83,c09ad7e6-8924-4415-9464-321056486512,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Raclette-Käse 3,99 A",Raclette-Käse,1.000,piece,3.99,None,0.5,True,Lidl,2025-12-30,good
84,a379e4df-be3e-40e0-9e68-ceb359760928,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Bioland Tofu natur 2,29Xx% 2 4,53 A","Bioland Tofu natur 2,29Xx% 2",2.000,piece,4.53,None,0.9,False,Lidl,2025-12-30,good
85,1bfb0b02-5d50-476e-8713-9f4bbf441d94,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Schott.Räucherlachs 2,99 A",Schott.Räucherlachs,1.000,piece,2.99,None,0.5,True,Lidl,2025-12-30,good
86,21248490-2a10-4b46-bbe2-dd617146419e,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Bio Griıech. Feta 2,89 A",Bio Griıech. Feta,1.000,piece,2.89,None,0.5,True,Lidl,2025-12-30,good
87,35940552-6f8b-41d4-9387-fa7608ebf9d8,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Griech, Joghurt 2% 2,29 A","Griech, Joghurt",1.000,piece,2.29,None,0.5,True,Lidl,2025-12-30,good
88,71b65965-3135-4192-9583-2f4de5704385,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Kräuterbutter 1,19 A",Kräuterbutter,1.000,piece,1.19,None,0.5,True,Lidl,2025-12-30,good
89,a64ca184-6b6d-491d-9c9a-e9f8b7649d4c,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Hummus Ras el-Hanout 0,99 A",Hummus Ras el-Hanout,1.000,piece,0.99,None,0.5,True,Lidl,2025-12-30,good
90,2385a8a8-c69d-463a-82d4-62e19ee3109f,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Spreewälder Gurken 2,59 A",Spreewälder Gurken,1.000,piece,2.59,None,0.5,True,Lidl,2025-12-30,good
91,6113e996-4846-4cb3-a368-f65c89390cff,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Oro d,P stück.Tomate 1,99 A","Oro d,P stück.Tomate",1.000,piece,1.99,None,0.5,True,Lidl,2025-12-30,good
92,00d083bd-981e-4c3a-9a92-b54852784508,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Don Papa Baroko 40% 29,99 B",Don Papa Baroko,1.000,piece,29.99,None,0.5,True,Lidl,2025-12-30,good
93,53125fd8-1771-4d9f-95ba-86525340f4af,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Harry KörnerSandwich 2,49 A",Harry KörnerSandwich,1.000,piece,2.49,None,0.5,True,Lidl,2025-12-30,good
94,c20091cf-3722-4ff0-9893-4fed7b71f094,5cc46c1d-f75c-46cd-9894-056033f665ac,WhatsApp Image 2026-07-16 at 13.05.29.jpeg,"Cashewkerne 200g 2,99 A",Cashewkerne,200.000,g,2.99,None,0.9,False,Lidl,2025-12-30,good

## Export (optional)

Writes the two tables to disk next to this notebook, for downstream analysis without re-running OCR.

In [7]:
df_receipts.to_csv(REPO_ROOT / "receipt_extraction_receipts.csv", index=False)
df_items.to_csv(REPO_ROOT / "receipt_extraction_items.csv", index=False)
df_combined.to_csv(REPO_ROOT / "receipt_extraction_combined.csv", index=False)
print("Saved:")
print(" -", REPO_ROOT / "receipt_extraction_receipts.csv")
print(" -", REPO_ROOT / "receipt_extraction_items.csv")
print(" -", REPO_ROOT / "receipt_extraction_combined.csv")

Saved:
 - /Users/stuartkasemeier/Documents/Work/07-Arbeitslosigkeit/ai_project_management/neuefische_course/AIPM_capstone_project_supermarket_optimizer/receipt_extraction_receipts.csv
 - /Users/stuartkasemeier/Documents/Work/07-Arbeitslosigkeit/ai_project_management/neuefische_course/AIPM_capstone_project_supermarket_optimizer/receipt_extraction_items.csv
 - /Users/stuartkasemeier/Documents/Work/07-Arbeitslosigkeit/ai_project_management/neuefische_course/AIPM_capstone_project_supermarket_optimizer/receipt_extraction_combined.csv

## Matching preview: BLS / OFF / fallback category

For inspection only. For each parsed item's `normalized_name`, this calls the real matching services directly (no reimplementation):

- `services/bls_matcher.match_product_bls` — the BLS match the tiered resolver would pick, plus `services/bls_matcher.search_bls` — the raw top-5 closest BLS candidates by name similarity (independent of whether any clears the match threshold).
- `services/matcher.match_product` — the OpenFoodFacts match the tiered resolver would pick, plus `services/off_api.search_products` — the raw top-5 closest OFF candidates.
- `services/fallback_categories._canonical_category` — the category a rough nutrition estimate would use if neither BLS nor OFF produced a usable match (same call the offline parser itself makes, `_canonical_category(None, name)`).

This makes real network calls to the public OpenFoodFacts search API (cached on disk in `_off_cache.json` after the first call, same as the running app) and scans the in-memory BLS reference table already loaded by `bls_matcher.py`. Nothing is written to Supabase.

In [8]:
from backend.app.services import bls_matcher, off_api, fallback_categories
from backend.app.services.matcher import match_product
from backend.app.services.text_similarity import token_similarity


def _off_match_str(name: str):
    m = match_product(name)
    if m is None:
        return None
    return f"{m.matched_name} [off_id={m.off_id}] conf={m.confidence:.2f} ({m.match_type.value})"


def _off_top5_str(name: str, page_size: int = 5):
    candidates = off_api.search_products(name, page_size=page_size)
    scored = []
    for p in candidates:
        display = off_api.product_display_name(p) or "(no name)"
        scored.append(f"{display} ({token_similarity(name, display):.2f})")
    return " | ".join(scored) if scored else None


def _bls_match_str(name: str):
    m = bls_matcher.match_product_bls(name)
    if m is None:
        return None
    return f"{m['matched_name']} [bls_code={m['bls_code']}] conf={m['confidence']:.2f} ({m['match_type']})"


def _bls_top5_str(name: str, page_size: int = 5):
    candidates = bls_matcher.search_bls(name, page_size=page_size)
    return " | ".join(f"{c['name_de']} ({c['score']:.2f})" for c in candidates) if candidates else None


bls_match, bls_top5, off_match, off_top5, fallback_cat = [], [], [], [], []
query_names = df_items["normalized_name"].fillna(df_items["raw_name"])

for i, name in enumerate(query_names):
    bls_match.append(_bls_match_str(name))
    bls_top5.append(_bls_top5_str(name))
    off_match.append(_off_match_str(name))
    off_top5.append(_off_top5_str(name))
    fallback_cat.append(fallback_categories._canonical_category(None, name))
    if (i + 1) % 20 == 0 or (i + 1) == len(query_names):
        print(f"matched {i + 1}/{len(query_names)} items")

df_items["BLS_match"] = bls_match
df_items["closest_5_after_BLS"] = bls_top5
df_items["OFF_match"] = off_match
df_items["closest_5_after_OFF"] = off_top5
df_items["Fallback_category"] = fallback_cat

df_items

matched 20/119 items

matched 40/119 items

matched 60/119 items

matched 80/119 items

matched 100/119 items

matched 119/119 items

,item_id,receipt_id,file_name,raw_name,normalized_name,quantity,unit,price,matched_product_id,confidence,uncertain,BLS_match,closest_5_after_BLS,OFF_match,closest_5_after_OFF,Fallback_category
0,1827153b-b012-453b-926f-c3df158cae91,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Banane Fair Bio 2,35 A",Banane Fair Bio,1.182,kg,2.35,None,0.5,True,Banane roh [bls_code=F503100] conf=0.85 (fuzzy),"Banane roh (0.85) | Bananenchips frittiert, gesüßt (0.85) | Kochbanane roh (...",Banane BIO [off_id=3250393062582] conf=1.00 (fuzzy),Barres céréales Banane Chocolat noir (0.85) | Banane BIO (1.00) | (no name) ...,fruit
1,592f30db-ea4d-4418-a314-b03d96f7a074,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Zwiebeln weiß 1,28 A",Zwiebeln weiß,0.356,kg,1.28,None,0.5,True,"Weiße Rübe/Wasserrübe/Herbstrübe, roh [bls_code=G614100] conf=0.85 (fuzzy)","Weiße Rübe/Wasserrübe/Herbstrübe, roh (0.85) | Heilbutt/Weißer Heilbutt, roh...",Zwiebeln weiss [off_id=4063367118326] conf=0.89 (fuzzy),Zwiebeln weiss (0.89) | Gemüse - Zwiebeln weiss (0.85),vegetable
2,97af5108-17a5-480b-af76-e0f0b2e841f3,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Bioland Zucchini 1,49 A",Bioland Zucchini,1.000,piece,1.49,None,0.5,True,"Schwein Speck, ohne Schwartenzug (S VII) roh [bls_code=U605700] conf=0.85 (f...","Schwein Speck, ohne Schwartenzug (S VII) roh (0.85) | Eierteigwaren Tortello...",NaN,Zucchini (0.85),other
3,c3138c2f-675b-4c0d-9b6b-37c3472fcd15,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Petersilie 1,39 A",Petersilie,1.000,piece,1.39,None,0.5,True,Petersilienblatt getrocknet [bls_code=G250400] conf=0.85 (fuzzy),Petersilienblatt getrocknet (0.85) | Petersilienblatt roh (0.85) | Wurzelpet...,Petersilie getrocknet [off_id=20226558] conf=0.85 (fuzzy),Pesto Basilico e Rucula (0.48) | Petersilie getrocknet (0.85) | Petersilie -...,other
4,517fc874-ad36-4723-9408-0ba10f7861d5,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Bio Limetten 1,99 A",Bio Limetten,1.000,piece,1.99,None,0.5,True,Limette roh [bls_code=F602100] conf=0.85 (fuzzy),Limette roh (0.85) | Limettensaft (0.85) | Limettensaft Konzentrat (0.85) | ...,Limetten Saft [off_id=4003387006012] conf=0.85 (fuzzy),Limetten Saft (0.85) | Bio Limetten (1.00) | Bio-Fairtrade-Limetten (1.00) |...,other
5,c9574418-4e27-40cd-b21c-4fab8a121b8b,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Weidemilch 3,8% 1,19 A",Weidemilch,1.000,piece,1.19,None,0.5,True,"Milch fettarm, frisch, 1,5 % Fett, pasteurisiert [bls_code=M111200] conf=0.8...","Milch fettarm, frisch, 1,5 % Fett, pasteurisiert (0.85) | H-Milch fettarm, 1...",Weidemilch [off_id=4061462544262] conf=1.00 (exact),Frische Weidemilch (0.85) | frische Weidemilch (0.85) | Deutsche Markenbutte...,dairy
6,5cc0d5e7-9b8b-483e-a5c4-0159e175d6a9,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Exquisa fitlineNatur 1,59 A",Exquisa fitlineNatur,1.000,piece,1.59,None,0.5,True,"Cerealien aus Vollkornweizenschrot, gesüßt, ungefüllt, Natur/Frucht/Schokola...","Cerealien aus Vollkornweizenschrot, gesüßt, ungefüllt, Natur/Frucht/Schokola...",NaN,NaN,other
7,6bf23279-4d79-4a28-a525-71f9f4ee9f2c,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Bio-Eier OKT 10er 3,99 A",Bio-Eier OKT 10er,1.000,piece,3.99,None,0.5,True,"Rhabarberkompott mit einer Zuckerart und Süßungsmitteln, Konserve [bls_code=...","Rhabarberkompott mit einer Zuckerart und Süßungsmitteln, Konserve (0.89) | P...",NaN,NaN,protein
8,1edac537-14b2-4b64-a470-76646701ce9e,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Bio Müsli Schoko Kn. 2,65 A",Bio Müsli Schoko Kn,1.000,piece,2.65,None,0.5,True,"Cerealien extrudiert, gesüßt, ungefüllt, mit Frucht-/Honig-/Karamell-/Schoko...","Cerealien extrudiert, gesüßt, ungefüllt, mit Frucht-/Honig-/Karamell-/Schoko...",NaN,NaN,grain
9,cd8d9096-6e3c-420a-b96e-c2e89daa45c6,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Lava Bar Cookie 1,69 A",Lava Bar Cookie,1.000,piece,1.69,None,0.5,True,"Milchschokoladen-Riegel gefüllt mit Karamell, gerösteten Erdnüssen und Candy...","Milchschokoladen-Riegel gefüllt mit Karamell, gerösteten Erdnüssen und Candy...",LAVA BAR COOKIES & CREAM [off_id=4260639153782] conf=1.00 (fuzzy),LAVA BAR COOKIES & CREAM (1.00),other
10,9ea14ff0-24a4-4c65-ad0c-37256157f77e,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Dinkelschnitte 1,29 A",Dinkelschnitte,1.000,piece,1.29,None,0.5,True,Dinkel Vollkornmehl [bls_code=C235000] conf=0.85 (fuzzy),"Dinkel Vollkornmehl (0.85) | Dinkel Grieß (0.85) | Dinkel ganzes Korn, roh (...",Dinkelschnitte [off_id=4061458128841] conf=1.00 (exact),Dinkelschnitte (1.00),other
11,e93b8d45-287f-4410-a47f-e67a3d2d9a7b,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Walnusskerne 2,99 A",Walnusskerne,1.000,piece,2.99,None,0.5,True,Nuss-Nougat-Creme [bls_code=S145000] conf=0.85 (fuzzy),"Nuss-Nougat-Creme (0.85) | Schwein Nuss, roh (0.85) | Walnuss (0.85) | Schwe...",Walnusskerne [off_id=4008258130018] conf=1.00 (exact),Walnusskerne naturbelassen (0.85) | Walnusskerne (1.00) | WALNUSS-KERNE (0.9...,other
12,80f8e9ca-c1bd-44f9-b400-db164f8495af,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Bio Cashewkerne 2,45 A",Bio Cashewkerne,1.000,piece,2.45,None,0.5,True,Cashewkern [bls_code=H170100] conf=0.85 (fuzzy),"Cashewkern (0.85) | Cashewnussmus (0.85) | Käsealternative, Basis Cashewkern...",Bio Cashewkerne [off_id=4335619016743] conf=1.00 (exact),Bio Cashewkerne (1.00) | Cashewkerne (0.85) | Cashewbruch (0.64) | Bio-Vital...,other
13,cf4cd0f6-9400-48c4-acd2-a4e4484b7648,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Rinderhackfleisch 5% 5,99 A",Rinderhackfleisch,1.000,piece,5.99,None,0.5,True,"Schwein Fettwamme, ohne Schwarten, geringer Magerfleischanteil (S XI) roh [b...","Schwein Fettwamme, ohne Schwarten, geringer Magerfleischanteil (S XI) roh (0...",NaN,Frisches Rinderhackfleisch Bio (0.85) | Rinderhackfleisch (1.00) | ALDI MEIN...,protein
14,04698622-e165-4091-bfe4-1ad84c260e62,1b66426a-f508-4e82-8c63-dae566dd3202,2026.06.30_23001961862026063034796.jpg.png,"Puten-Geschnetzeltes 4,59 x 2 9,18 A",Puten-Geschnetzeltes,2.000,piece,9.18,None,0.9,False,Putenei roh [bls_code=E151100] conf=0.85 (fuzzy),"Putenei roh (0.85) | Pute Fleisch, mit Haut, roh (0.85) | Pute Brust, ohne H...",Puten-Geschnetzelte [off_id=4058204567160] conf=0.97 (exact),Familien-Packung Puten-Geschnetzeltes (0.85) | Puten-Geschnetzelte (0.97) | ...,other
15,55291075-9ffb-4162-8ccf-166c07fed72d,8d554238-2f93-4096-9d0c-e0a516bcda25,IMG_1928.JPG,"745 7] Geg, BAR EUR 1,20 EST","745 7] Geg, BAR EUR",1.000,piece,1.20,None,0.5,True,"Milchschokoladen-Riegel gefüllt mit Karamell, gerösteten Erdnüssen und Candy...","Milchschokoladen-Riegel gefüllt mit Karamell, gerösteten Erdnüssen und Candy...",NaN,NaN,other
16,ab7d696c-4b00-4199-a13a-ff6ab59c07fa,8d554238-2f93-4096-9d0c-e0a516bcda25,IMG_1928.JPG,"Sn DS B= 7,0% 1,11 0,08 1,19 nm","Sn DS B= 1,11 0,08",1.000,piece,1.19,None,0.5,True,NaN,"Pilsner Bier, 0,0 % vol (0.44) | Ascorbinsäure (E 300) (0.36) | Weizen Mehl,...",NaN,NaN,other
17,193062e7-7777-4c7b-9262-ed4041379b04,30bb7241-c4aa-4d61-ba68-9eeffa94c335,IMG_1929.JPG,"‚ Miracel Whip 1,49€x 3 4,47 AW",Miracel Whip,3.000,piece,4.47,None,0.9,False,Hagebutte roh [bls_code=F402100] conf=0.85 (fuzzy),Hagebutte roh (0.85) | Schlagsahne mind. 36 % Fett (0.85) | Sahnestandmittel...,Miracel Whip [off_id=4000339057726] conf=1.00 (exact),Miracel Whip Mayonnaise (0.85) | Miracel Whip Balance (0.85) | Miracel Whip ...,other
18,ba126edb-6968-42b9-96cc-1f2c35e37476,30bb7241-c4aa-4d61-ba68-9eeffa94c335,IMG_1929.JPG,"| Frischfi,erm,BED 3,98 A","Frischfi,erm,BED",1.000,piece,3.98,None,0.5,True,Weizen Keim [bls_code=C114000] conf=0.86 (fuzzy),Weizen Keim (0.86) | Weizenkeimöl (0.86) | Roggenvollkornknäckebrot mit Lein...,NaN,NaN,other
19,d131a00e-3aef-44b9-87b0-4d9c1af7c5f0,30bb7241-c4aa-4d61-ba68-9eeffa94c335,IMG_1929.JPG,"/ Lang.Cremiss.Eis 1,89 AM",Lang.Cremiss.Eis,1.000,piece,1.89,None,0.5,True,Fürst-Pückler-Eis [bls_code=Y999140] conf=1.00 (fuzzy),"Fürst-Pückler-Eis (1.00) | Reis poliert, roh (0.86) | Reis parboiled, polier...",NaN,NaN,other
20,7a4f68fa-72d1-446a-b290-807f3b1cc19c,30bb7241-c4aa-4d61-ba68-9eeffa94c335,IMG_1929.JPG,"Harry Sonntag 0,15 € x 5 0,75 AM",Harry Sonntag,5.000,piece,0.75,None,0.9,False,"Sauerkirsche gezuckert, Konserve, abgetropft [bls_code=F212902] conf=0.73 (f...","Sauerkirsche gezuckert, Konserve, abgetropft (0.73) | Sherry medium dry (0.7...",NaN,NaN,other
21,afc3e0a0-413f-45c3-9895-d152be5d0a74,30bb7241-c4aa-4d61-ba68-9eeffa94c335,IMG_1929.JPG,"/ THUER ,METT/HACKEP. 1,20 AM","THUER ,METT/HACKEP",1.000,piece,1.20,None,0.5,True,Streichmettwurst/Streichmettwurst mit Zwiebeln [bls_code=W112200] conf=0.85 ...,Streichmettwurst/Streichmettwurst mit Zwiebeln (0.85) | Mettwurst gekocht (0...,NaN,NaN,other
22,c6fdcaf2-284c-49fb-88f1-c1f715c64821,30bb7241-c4aa-4d61-ba68-9eeffa94c335,IMG_1929.JPG,"| THUER.METT/HACKEP, 1,21 AW",THUER.METT/HACKEP,1.000,piece,1.21,None,0.5,True,Streichmettwurst/Streichmettwurst mit Zwiebeln [bls_code=W112200] conf=0.85 ...,Streichmettwurst/Streichmettwurst mit Zwiebeln (0.85) | Mettwurst gekocht (0...,NaN,NaN,other
23,b5b14672-8439-41f0-aeef-9c6059ca3c69,30bb7241-c4aa-4d61-ba68-9eeffa94c335,IMG_1929.JPG,"_ GURKEN ‚ 0,49€x% 2 0,98 AM",GURKEN ‚,2.000,piece,0.98,None,0.9,False,Gurke roh [bls_code=G520100] conf=0.85 (fuzzy),Gurke roh (0.85) | Gurke gesäuert (Gewürzgurke) abgetropft (0.85) | Gurke ge...,Gurken [off_id=8480000295408] conf=0.86 (fuzzy),Cornichons Gurken (0.85) | Gurken (0.86) | Gewürzgurken (0.85) | KNAX Gewürz...,vegetable
24,adedcd12-0740-413c-8770-fd0b07183fbe,30bb7241-c4aa-4d61-ba68-9eeffa94c335,IMG_1929.JPG,"‚ Vand.Mai Gouda 2,58 AW",Vand.Mai Gouda,1.000,piece,2.58,None,0.5,True,Mais roh [bls_code=C341000] conf=0.86 (fuzzy),Mais roh (0.86) | Mais Mehl (0.86) | Mais Stärke (0.86) | Mais Grieß (0.86) ...,NaN,NaN,other
25,dd81621a-b787-4bdd-bffe-e5c490505d2f,0c84d1cd-e2b1-4873-af7a-31d06e600720,IMG_1937.PNG,"Bulgur Rote Beete 2,49 B",Bulgur Rote Beete,1.000,piece,2.49,None,0.5,True,"Rote Rübe/Rote Bete, roh [bls_code=G613100] conf=0.89 (fuzzy)","Rote Rübe/Rote Bete, roh (0.89) | Rote Rübe/Rote Bete, gedünstet (0.89) | Ro...",Rote Beete Bulgur Salat [off_id=4260232639478] conf=0.85 (fuzzy),Rote Beete Bulgur Salat (0.85),other
26,2d0ab919-23f3-4b5c-9972-6c76d9ffd534,b8398cde-f425-4a5c-985f-7f40f2c6276e,Netto_Kassenbon_20260702-191137.pdf,Favora Topa 3lg. 10x220BL,Favora Topa 3lg. 10x220BL,1.000,piece,3.85,None,0.9,False,Altbier [bls_code=P153000] conf=0.85 (fuzzy),"Altbier (0.85) | Rind Oberschale, roh (0.85) | Rind Roulade (Oberschale) roh...",NaN,NaN,other
27,f24d9a9a-8fa0-4922-a4e0-b17c395037fa,b8398cde-f425-4a5c-985f-7f40f2c6276e,Netto_Kassenbon_20260702-191137.pdf,Pri.Zugb.muellbtl.25x60L,Pri.Zugb.muellbtl.25,60.000,l,1.89,None,0.9,False,"Rind Hochrippe, roh [bls_code=U235100] conf=0.75 (fuzzy)","Rind Hochrippe, roh (0.75) | Rind Hochrippe, gebraten ohne Fett (Ofen) (0.75...",NaN,NaN,other
28,75364570-9157-417c-8ed2-4165a77d6298,b8398cde-f425-4a5c-985f-7f40f2c6276e,Netto_Kassenbon_20260702-191137.pdf,BesteErnte Himbeeren 500g,BesteErnte Himbeeren,500.000,g,4.99,None,0.9,False,Himbeere roh [bls_code=F302100] conf=0.85 (fuzzy),Himbeere roh (0.85) | Wald-Himbeere roh (0.85) | Weizenbier kristallklar (0....,NaN,NaN,fruit
29,4cb8bdaf-233b-4ddf-b22c-beedf7bcedc5,b8398cde-f425-4a5c-985f-7f40f2c6276e,Netto_Kassenbon_20260702-191137.pdf,Ostm.Paprika ger. gem.50g,Ostm.Paprika ger. gem,50.000,g,2.59,None,0.9,False,Weizen Keim [bls_code=C114000] conf=0.86 (fuzzy),Weizen Keim (0.86) | Weizenkeimöl (0.86) | Roggenvollkornknäckebrot mit Lein...,NaN,NaN,vegetable
30,dcb6f9be-4339-43ff-81bd-2d586f0bc6c0,cc8c3543-623d-4ff6-ae83-a22028742571,Netto_Kassenbon_20260707-180115.pdf,Beste Ernte Kichererbsen 265g,Beste Ernte Kichererbsen,265.000,g,0.59,None,0.9,False,"Rote Rübe/Rote Bete, roh [bls_code=G613100] conf=0.89 (fuzzy)","Rote Rübe/Rote Bete, roh (0.89) | Ente Leber, roh (0.89) | Ente Fleisch, mit...","Kichererbsen, BESTE ERNTE [off_id=4316268577298] conf=0.85 (fuzzy)","Kichererbsen, BESTE ERNTE (0.85) | Kichererbsen 265 (0.85) | Kichererbsen (0...",other
31,45e66d24-8b19-45e7-9019-73f10fb8d2ba,cc8c3543-623d-4ff6-ae83-a22028742571,Netto_Kassenbon_20260707-180115.pdf,Beste Ernte Kidneybohnen 255g,Beste Ernte Kidneybohnen,255.000,g,0.69,None,0.9,False,"Rote Rübe/Rote Bete, roh [bls_code=G613100] conf=0.89 (fuzzy)","Rote Rübe/Rote Bete, roh (0.89) | Ente Leber, roh (0.89) | Ente Fleisch, mit...",Kidney Bohnen [off_id=4316268668286] conf=0.85 (fuzzy),Kidney Bohnen (0.85) | Kidneybohnen (0.85) | Chili Beans (0.60) | Konserve K...,protein
32,97246d4b-c38d-43e9-be02-7bb5ab8c85b6,cc8c3543-623d-4ff6-ae83-a22028742571,Netto_Kassenbon_20260707-180115.pdf,Irische Butter Kerrygold 250g,Irische Butter Kerrygold,250.000,g,1.49,None,0.9,False,Kirsche kandiert (Belegkirsche) [bls_code=S472200] conf=0.86 (fuzzy),Kirsche kandiert (Belegkirsche) (0.86) | Fruchtsaftgetränk Kirsche (0.86) | ...,Kerrygold Irische Butter [off_id=4001954161904] conf=0.85 (fuzzy),Kerrygold Irische Butter (0.85) | Irische Butter gesalzen (0.85) | Kerrygold...,dairy
33,ece54d8d-31dd-46b8-9ccf-a081e05abced,cc8c3543-623d-4ff6-ae83-a22028742571,Netto_Kassenbon_20260707-180115.pdf,Bio BB Feta 200g,Bio BB Feta,200.000,g,2.69,None,0.9,False,Feta mind. 45 % Fett i. Tr. [bls_code=M012200] conf=0.85 (fuzzy),Feta mind. 45 % Fett i. Tr. (0.85) | Schafskäse (Feta) mit Tomaten und Olive...,NaN,NaN,other
34,1be0e269-aa35-4dbf-8f5e-9045a652cc0f,cc8c3543-623d-4ff6-ae83-a22028742571,Netto_Kassenbon_20260707-180115.pdf,Bio Paprika Mix 400g,Bio Paprika Mi,400.000,g,1.99,None,0.9,False,"Gemüsepaprika grün, roh [bls_code=G541100] conf=0.85 (fuzzy)","Gemüsepaprika grün, roh (0.85) | Gemüsepaprika rot, roh (0.85) | Gemüsepapri...",Stone ground chips paprika [off_id=7640102310992] conf=0.85 (fuzzy),Stone ground chips paprika (0.85),vegetable
35,6a4c07c6-d254-4ca4-8e3d-9f319ad1551b,cc8c3543-623d-4ff6-ae83-a22028742571,Netto_Kassenbon_20260707-180115.pdf,Minigurken 750g,Minigurken,750.000,g,1.99,None,0.9,False,Roquefort mind. 50 % Fett i. Tr. [bls_code=M012100] conf=0.85 (fuzzy),Roquefort mind. 50 % Fett i. Tr. (0.85) | Gorgonzola mind. 48 % Fett i. Tr. ...,Minigurken [off_id=4063367308642] conf=1.00 (exact),"Minigurken Klasse 1 (0.85) | Minigurken (1.00) | Boosty Bites, Minigurken (0...",vegetable
36,0a2f3d61-f330-4467-a612-2a3bb0d67dc6,cc8c3543-623d-4ff6-ae83-a22028742571,Netto_Kassenbon_20260707-180115.pdf,Minipflaumen Tomaten 500g,Minipflaumen Tomaten,500.000,g,1.99,None,0.9,False,Roquefort mind. 50 % Fett i. Tr. [bls_code=M012100] conf=0.85 (fuzzy),Roquefort mind. 50 % Fett i. Tr. (0.85) | Gorgonzola mind. 48 % Fett i. Tr. ...,NaN,Minipflaumen Rispentomaten (0.87) | Minipflaumen tomaten (1.00),vegetable
37,edf22484-658c-4782-b921-d16f8dfa320e,cc8c3543-623d-4ff6-ae83-a22028742571,Netto_Kassenbon_20260707-180115.pdf,Bananen Lose MT,Bananen Lose MT,1.266,kg,1.63,None,0.9,False,Banane roh [bls_code=F503100] conf=0.85 (fuzzy),"Banane roh (0.85) | Bananenchips frittiert, gesüßt (0.85) | Fruchtmischung (...",NaN,NaN,fruit
38,7e6ee9c0-9991-4ad7-bd58-9eb3c91dea3a,cc8c3543-623d-4ff6-ae83-a22028742571,Netto_Kassenbon_20260707-180115.pdf,Lauchzwiebeln,Lauchzwiebeln,1.000,piece,0.55,None,0.9,False,"Porree/Lauch, roh [bls_code=G470100] conf=0.85 (fuzzy)","Porree/Lauch, roh (0.85) | Schwein Bauch (wie gewachsen) roh (0.85) | Streic...","Couscoussalat mit Paprika, Salzlakenkäse und Lauchzwiebeln [off_id=433725603...","Couscoussalat mit Paprika, Salzlakenkäse und Lauchzwiebeln (0.85) | Obazda L...",vegetable
39,30b46fef-1ce4-48a9-a2d8-0cc8f38602f9,cc8c3543-623d-4ff6-ae83-a22028742571,Netto_Kassenbon_20260707-180115.pdf,Apfel Pink Lady Lose,Apfel Pink Lady Lose,0.182,kg,0.54,None,0.9,False,Apfelwein [bls_code=P353100] conf=0.85 (fuzzy),Apfelwein (0.85) | Apfel roh (0.85) | Apfel getrocknet (0.85) | Granatapfel ...,NaN,NaN,fruit
40,c90aacff-eb4a-4099-9997-d385d3fceb9c,34440959-7870-49fe-85cd-7a227d4cbb39,Netto_Kassenbon_20260709-172131.pdf,VL Eier FH 10ST,VL Eier FH,10.000,piece,2.99,None,0.9,False,"Rhabarberkompott mit einer Zuckerart und Süßungsmitteln, Konserve [bls_code=...","Rhabarberkompott mit einer Zuckerart und Süßungsmitteln, Konserve (0.89) | P...",NaN,NaN,protein
41,1d24e3f8-23b8-44e2-8301-1e005e880436,34440959-7870-49fe-85cd-7a227d4cbb39,Netto_Kassenbon_20260709-172131.pdf,LiekenUrkornMehrkorn500g,LiekenUrkornMehrkorn,500.000,g,1.49,None,0.9,False,"Hafer ganzes Korn, roh [bls_code=C131000] conf=0.85 (fuzzy)","Hafer ganzes Korn, roh (0.85) | Gerste ganzes Korn, roh (0.85) | Getreidebra...",NaN,NaN,other
42,6235094a-2a6b-4e85-b71e-aabefd52b123,34440959-7870-49fe-85cd-7a227d4cbb39,Netto_Kassenbon_20260709-172131.pdf,Ostmann.Oregano gerebelt.25g,Ostmann.Oregano gerebelt,25.000,g,2.99,None,0.9,False,Bel Paese mind. 50 % Fett i. Tr. [bls_code=M619700] conf=0.85 (fuzzy),"Bel Paese mind. 50 % Fett i. Tr. (0.85) | Kokos Fruchtfleisch, geraspelt, ge...",NaN,NaN,other
43,1be4f37d-4e2c-45c1-b97f-3acfe85da251,34440959-7870-49fe-85cd-7a227d4cbb39,Netto_Kassenbon_20260709-172131.pdf,Ostm.Rosmarin geschn.50g,Ostm.Rosmarin geschn,50.000,g,2.99,None,0.9,False,Rindergeschnetzeltes [bls_code=Y144512] conf=0.85 (fuzzy),"Rindergeschnetzeltes (0.85) | Lammrücken gebraten im Ofen, mit Rosmarin und ...",NaN,NaN,other
44,350f554f-ee1d-4830-a22f-a7a0d037ca20,34440959-7870-49fe-85cd-7a227d4cbb39,Netto_Kassenbon_20260709-172131.pdf,AIRWAVESCoolCassis50ST,AIRWAVESCoolCassis,50.000,piece,2.95,None,0.9,False,"Mettwurst luftgetrocknet, energiereduziert [bls_code=W153100] conf=0.85 (fuzzy)","Mettwurst luftgetrocknet, energiereduziert (0.85) | Mettwurst luftgetrocknet...",NaN,NaN,other
45,c6afbb70-9b4c-493d-ba6b-39e4ff926e0f,4e42fe7b-680a-4843-9139-e92784c3cc31,Netto_Kassenbon_20260713-170620.pdf,Beste Ernte Kidneybohnen 255g,Beste Ernte Kidneybohnen,255.000,g,0.69,None,0.9,False,"Rote Rübe/Rote Bete, roh [bls_code=G613100] conf=0.89 (fuzzy)","Rote Rübe/Rote Bete, roh (0.89) | Ente Leber, roh (0.89) | Ente Fleisch, mit...",Kidney Bohnen [off_id=4316268668286] conf=0.85 (fuzzy),Kidney Bohnen (0.85) | Kidneybohnen (0.85) | Chili Beans (0.60) | Konserve K...,protein
46,f4da6489-95ec-415e-8272-e017f469b7d6,4e42fe7b-680a-4843-9139-e92784c3cc31,Netto_Kassenbon_20260713-170620.pdf,VL Eier FH 10ST,VL Eier FH,10.000,piece,2.99,None,0.9,False,"Rhabarberkompott mit einer Zuckerart und Süßungsmitteln, Konserve [bls_code=...","Rhabarberkompott mit einer Zuckerart und Süßungsmitteln, Konserve (0.89) | P...",NaN,NaN,protein
47,15603730-0ae4-452d-a56c-abece0adcc8f,4e42fe7b-680a-4843-9139-e92784c3cc31,Netto_Kassenbon_20260713-170620.pdf,Beste Ernte Kichererbsen 265g,Beste Ernte Kichererbsen,265.000,g,0.59,None,0.9,False,"Rote Rübe/Rote Bete, roh [bls_code=G613100] conf=0.89 (fuzzy)","Rote Rübe/Rote Bete, roh (0.89) | Ente Leber, roh (0.89) | Ente Fleisch, mit...","Kichererbsen, BESTE ERNTE [off_id=4316268577298] conf=0.85 (fuzzy)","Kichererbsen, BESTE ERNTE (0.85) | Kichererbsen 265 (0.85) | Kichererbsen (0...",other
48,34d777b0-3c3d-4289-bb97-7bda672883ab,4e42fe7b-680a-4843-9139-e92784c3cc31,Netto_Kassenbon_20260713-170620.pdf,Lieken Urkorn Fitnessbrot 500g,Lieken Urkorn Fitnessbrot,500.000,g,1.89,None,0.9,False,"Hafer ganzes Korn, roh [bls_code=C131000] conf=0.85 (fuzzy)","Hafer ganzes Korn, roh (0.85) | Gerste ganzes Korn, roh (0.85) | Gemüsepapri...",Fitnessbrot mit 5 % Ölsaaten [off_id=4009249002277] conf=0.85 (fuzzy),Fitnessbrot mit 5 % Ölsaaten (0.85),grain

### Re-export with matching-preview columns

Overwrites the two item-level CSVs from the extraction step above with the same rows plus the five new columns; `receipt_extraction_receipts.csv` is untouched.

In [9]:
df_combined = df_items.merge(
    df_receipts[["receipt_id", "store", "purchase_date", "scan_quality"]],
    on="receipt_id",
    how="left",
    suffixes=("", "_receipt"),
)

df_items.to_csv(REPO_ROOT / "receipt_extraction_items.csv", index=False)
df_combined.to_csv(REPO_ROOT / "receipt_extraction_combined.csv", index=False)
print("Re-saved with matching-preview columns:")
print(" -", REPO_ROOT / "receipt_extraction_items.csv")
print(" -", REPO_ROOT / "receipt_extraction_combined.csv")

Re-saved with matching-preview columns:
 - /Users/stuartkasemeier/Documents/Work/07-Arbeitslosigkeit/ai_project_management/neuefische_course/AIPM_capstone_project_supermarket_optimizer/receipt_extraction_items.csv
 - /Users/stuartkasemeier/Documents/Work/07-Arbeitslosigkeit/ai_project_management/neuefische_course/AIPM_capstone_project_supermarket_optimizer/receipt_extraction_combined.csv